### ISSUE TITLE
Missing Yield details for WBTC (and USDT) deposit

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1000]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand YFI.
3. Manage.
4. Select WBTC or USDT from "From" dropdown.
5. Set amount values to MAX.

Expected:
Yield filelds expands and displayes yield details.

Actual:
![image](https://user-images.githubusercontent.com/98878781/153585288-76908cdd-5bc2-42ad-b4b4-d113a9be498b.png)

**Comment by lazarmitic** [comment]
This is ready for testing.

USDT now works.
WBTC is removed from the app.

**Comment by irinelT** [comment]
This is fixed.
