### ISSUE TITLE
In Withdraw UI, after token is approved, UI reverts to show Approve button again

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#1002]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/78982233/153588571-801a14ec-91a5-419b-85e5-db59db148ab0.png">

**Comment by irinelT** [comment]
Approved is checked as expected.

![image](https://user-images.githubusercontent.com/98878781/153855322-882664c2-4759-4f53-90c2-70722a744c5d.png)
