### ISSUE TITLE
Raise error notification when slippage too low 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#1003]
As a user
I want to see an error message notification when there is an issue with the slippage settings when withdrawing (other actions also)
So that I can adjust the slippage accordingly

**Comment by RTP2016** [comment]
Error message: 
"Slippage for this transaction is too low. Please adjust the slippage in the settings menu."

**Comment by RTP2016** [comment]
This is ready @lazarmitic @ShawTim

**Comment by lazarmitic** [comment]
This might be some other error. Can you expand those errors and check the fail reason?

**Comment by lazarmitic** [comment]
I tried to deposit with 0.01% slippage in same pool and deposit was successful, this is probably some other error (RPC issue maybe)?

![image](https://user-images.githubusercontent.com/7648077/157449707-2772a159-eb9f-40a7-94d7-16effe30f1aa.png)

**Comment by irinelT** [comment]
@lazarmitic Does this help?

![image](https://user-images.githubusercontent.com/98878781/157450995-e1019df5-0ad5-4f20-9934-1305ea9ec8fe.png)

**Comment by lazarmitic** [comment]
Just scroll it a bit to the right so that I can see whole message :)

**Comment by irinelT** [comment]
Or this? Can we have add "Fantom network error" on RPC issues like "Slippage for this transaction is too low. Please adjust the slippage in the settings menu." on slippage issues.

![image](https://user-images.githubusercontent.com/98878781/157452759-bffb4c09-1ead-41c3-9757-bbb7bdddc5b8.png)

**Comment by lazarmitic** [comment]
Previous one was better I think, but I couldn't see whole message.

We can definitely expand list of errors we handle (show info for).

**Comment by irinelT** [comment]
Here is the entire log.

[tempus-app-stage.web.app-1646833504242.log](https://github.com/tempus-finance/tempus-app/files/8215205/tempus-app-stage.web.app-1646833504242.log)

**Comment by lazarmitic** [comment]
This is definitely not a slippage error. That's why you don't see the message. I will try to reproduce the error you are getting  on my end. We can open new issue for it.

**Comment by irinelT** [comment]
The slippage error notification works.

![image](https://user-images.githubusercontent.com/98878781/159343226-29167592-1f24-43cd-a2ec-38dd88dc5764.png)
