### ISSUE TITLE
Plus icon should only be visible when there are multiple primitives to withdraw from

### ISSUE THREAD

**Issue by Olafkuusik** [tempus-finance/tempus-app#1008]
Bug appears: Transaction view -> Withdraw -> you have only 1 type of primitive in your current position
Should be: Plus icon only visible when there are multiple primitives to withdraw from.
![image](https://user-images.githubusercontent.com/22838368/153595988-94ef1915-612d-499e-9eaa-3be1d50d5426.png)

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/154233922-ccfaf1e7-43b2-43ca-aab7-ec28fe71662a.png)
