### ISSUE TITLE
StatisticsService.totalValueLockedUSD() doesnt support USDC on ethereum

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1013]
if we fall in the fallback logic (i.e. failing on `this.stats.totalValueLockedAtGivenRate()`),
`mul18f(rate, backingTokensLocked)` need to support precision
if the precision of token is not 18 it will return with a small number

**Comment by irinelT** [comment]
I do see USDC on Ethereum but depositing USDC is not working on Ethereum. 

@ShawTim If you could include the business requirement that is not functioning  going forward when creating tickets would be helpful for testing.

![image](https://user-images.githubusercontent.com/98878781/154817328-31ee9ab3-5392-4c6e-8dad-0be13b9e3b54.png)

**Comment by irinelT** [comment]
Closing the issue since we do support USDC on Ethereum. Depositing is currently disabled on Rari pools.
