### ISSUE TITLE
when CoinGecko data is cached, the precision doesnt take into account

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1015]
- you need to somehow be able to see the Rari pool, which is the only USDC pool on ethereum
- first load, good on TVL for Rari pool
- click to open any pool
- go back to dashboard (during the step please dont do page refresh or manually change URL)
- if it's not fixed, then you should see the TVL for Rari pool is $0
i run the app locally and change the code to force rari appears. 

**note** that we deployed new stats contract on ethereum as well, so it will never go to coingecko

**Comment by irinelT** [comment]
TVL on Rari looks good after executing the steps given above.

![image](https://user-images.githubusercontent.com/98878781/155189609-93b7c5f2-12ae-40c6-8499-740208d6ccb0.png)
