### ISSUE TITLE
App keeps refreshing when Wallet not connected

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1017]

**Comment by irinelT** [comment]
There is no more refresh when the wallet is not connected.

**Comment by irinelT** [comment]
@danieledamiani I think this broke the landing page of the app.

![image](https://user-images.githubusercontent.com/98878781/154025163-75d8cf69-cbb6-4cc1-a568-d4381c82cb94.png)

**Comment by irinelT** [comment]
There is a separate ticket for blank landing page issue so this one can be closed.
