### ISSUE TITLE
Blank dashboard after Disconnecting wallet 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#1026]
Steps taken
1. Ended Wallet Connect session via Metamask app 
2. Refreshed page
3. See blank dashboard (even after refreshing again)

Workaround 
Needed to connect the wallet again to make dashboard visible 
<img width="1252" alt="Screenshot 2022-02-14 at 15 03 47" src="https://user-images.githubusercontent.com/17698024/153889836-6c45ee16-4d09-40cd-81fe-aa5ee2f1a3f3.png">

**Comment by irinelT** [comment]
This is fixed.
![image](https://user-images.githubusercontent.com/98878781/154450055-2df26330-1af8-413c-a711-1f4cabdfb9ef.png)
