### ISSUE TITLE
"Estimated Amount Received" should not be zero

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1028]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand USDC.
3. Manage.
4. Withdraw.
4. Set "From" values to MAX.
5. Approve
6. Inspect "Estimated Amount Received"

Expected:
~ $60

Actual:
$0

Note: Switching from yvUSDC to USDC and back fixes the issue.

![image](https://user-images.githubusercontent.com/98878781/153900111-5c8693b1-61b3-4cd0-aec1-2d9af3b6be3f.png)

**Comment by RTP2016** [comment]
Seeing this issue: 
Withdrawal
1. Approved capital and yield tokens 
2. selected MAX for capital and yield 
3. Calculated 'TO' amount is blank 
4. Execute button disabled 

Workaround 
1. Delete input box and select max again 
2. Execute button becomes active & amount calculated

Before
<img width="1213" alt="Screenshot 2022-02-16 at 14 54 01" src="https://user-images.githubusercontent.com/17698024/154292114-eebd5cf8-4eed-4d11-9d3e-a087f99079da.png">

After
<img width="642" alt="Screenshot 2022-02-16 at 15 00 53" src="https://user-images.githubusercontent.com/17698024/154292269-54cc4b8a-1240-4d58-b1e3-f5238bf9e930.png">

**Comment by irinelT** [comment]
This is fixed.
