### ISSUE TITLE
Fantom Wallet Connect issue

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#1030]
Steps taken: 
1. Add FTM network to Metamask mobile 
2. Connect Tempus to Wallet Connect through QR
3. Wallet connects successfully

Issue 
4. Dashboard stats do not load 

Seems to be an issue with the app calling Alchemy endpoint with Ethereum RPC information and not using the Fantom RPC endpoints?  (see screenshot) 
<img width="1429" alt="Screenshot 2022-02-14 at 17 28 11" src="https://user-images.githubusercontent.com/17698024/153915514-552d61bd-d86a-4737-a1bf-86e087eecef3.png">

Open question (related)

Can we support network switching using Wallet Connect? Currently, it forces my Metamask

**Comment by ShawTim** [comment]
more inputs to add:

for metamask mobile, it works completely fine with ethereum through WalletConnect.
but if we add fantom opera network, and connect through WalletConnect:
- fail to get the APRs, as @RTP2016 posted
- when you refresh or disconnect, the dashboard will be empty without showing anything (the `localStorage` gets stuck)

**Comment by RTP2016** [comment]
Closing. Dashboard loads correctly.
