### ISSUE TITLE
Missing "At least 0.05 ETH must be left in your wallet to pay for gas fees" message

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1034]
Prerequest:

- Connect WalletConnect to Tempus App.
- You have no ETH.

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand ETH
3. Manage.
4. Deposit.
4. Select stETH in "From" dropdown.
5. Type in more than you have on your balance.

Expected:
- "Approve" button should be disabled.
- Warning should be displayed like on ETH
![image](https://user-images.githubusercontent.com/98878781/154046574-f2016f1a-117e-4949-a2e0-2ae2cd5374e5.png)

Actual:

![image](https://user-images.githubusercontent.com/98878781/154046334-8020bd6b-9dac-456b-b272-6f53be693701.png)

Note:
- This is also happening on USDC.

**Comment by danieledamiani** [comment]
- initially we were showing this warning only if the user was depositing ETH (no any other token) as he had to keep some to pay for the gas fees (Daniele)
- this makes sense as it's the gas paying asset being deposited. So this is as designed then. Can close. (Richard)

**Comment by RTP2016** [comment]
Irinel mentioned the second issue that was rolled into this issue specifically, that a user is able to approve an amount higher than they have in the wallet. I think it's probably logical to update this so it is limited by balance.

**Comment by irinelT** [comment]
I am still able to approve more deposit than i have on my balance.

![image](https://user-images.githubusercontent.com/98878781/154233448-c07c20f7-9751-43ba-8ebb-5c0f8b6fc74c.png)

**Comment by irinelT** [comment]
This issue is not reproducible any more.

![image](https://user-images.githubusercontent.com/98878781/154817542-a775195a-4a7f-4b3f-ad3e-fbc46a1d02ab.png)
