### ISSUE TITLE
Withdraw is not reflected on balance (until refresh)

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1036]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand USDC.
3. Manage.
4. Withdraw.
5. Set yvUSDC token in "From" dropbox
6. Execute withdrawal.
7. Navigate to Deposit.
8. Inspect the yvUSDC balance.

Expected:
- The balance contains the amount that is withddrawn.

Actual:
- Balance is incorrect until the refresh.

![image](https://user-images.githubusercontent.com/98878781/154064792-55f11b6a-24d6-44d3-9a98-55b340f74a6d.png)

**Comment by RTP2016** [comment]
This is still an issue
![Uploading Screenshot 2022-02-16 at 10.25.06.png…]()

**Comment by RTP2016** [comment]
<img width="1230" alt="Screenshot 2022-02-16 at 10 25 06" src="https://user-images.githubusercontent.com/17698024/154245475-fb8b733e-cdf5-41f7-81c1-50da439c33da.png">

**Comment by lazarmitic** [comment]
> <img width="1230" alt="Screenshot 2022-02-16 at 10 25 06" src="https://user-images.githubusercontent.com/17698024/154245475-fb8b733e-cdf5-41f7-81c1-50da439c33da.png">
> 

Current position is the value user has in the pool. Balance in the deposit 'from' box represents how many tokens user has in the wallet. I don't see anything out of place in this screenshot.

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/154272287-8f6c57b1-aa42-4b4d-9bfb-d4188b88e83b.png)

**Comment by irinelT** [comment]
@lazarmitic This issue is reproducipble on YFI.

![image](https://user-images.githubusercontent.com/98878781/154308719-8651ea54-61d2-4021-bdc2-3d8b07bc3a42.png)

**Comment by lazarmitic** [comment]
Hmm, might be a precision issue, I will test this tomorrow morning again.

**Comment by irinelT** [comment]
I think the precision is fine becouse it works perfectly after the refresh.

**Comment by lazarmitic** [comment]
Ah, I know what's wrong @danieledamiani updated balance provider for yeald bearing tokens and that works, but YFI is backing token and we need to update provider for backing tokens as well. Let's reopen this issue and fix backing token updates as well.

**Comment by irinelT** [comment]
This is fixed.
