### ISSUE TITLE
Incorrect APR

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1038]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand DAI.
3. Manage.
4. Navigate to Deposit.
5. Pick yvDAI in "From" dropdown box.
6. Type in 100 amount.
7. Inspect APR value.

Expected:
APR = 3.69 %

Actual:
APR = 10.06 %

![image](https://user-images.githubusercontent.com/98878781/154077821-281bb855-bc11-44b4-8962-624e562b6d70.png)

**Comment by lazarmitic** [comment]
APR is Anual Percentage Rate, duration of this pool is less then one year, so the principals you get do not match APR. APR is calculated in token value, not USD so you don't have to take into account USD value of tokens in the calculation.

Example:

If pool time to maturity is 1year and APR is 10% you will get 110 Principals for 100 backing tokens.

If pool time to maturity is 6 months and APR is 10% you will get 105 Principals for 100 backing tokens.

If pool time to maturity is 2 years and APR is 10% you will get 120 Principals for 100 backing tokens.

**Comment by irinelT** [comment]
That calculation makes sence and maches the UI. Closing the ticket.
