### ISSUE TITLE
Horrible label colors on GitHub

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1039]
Please change the GitHub label colors or delegate to someone from Design team.
The label colors can be edited from https://github.com/tempus-finance/tempus-app/issues/labels.

Sugegested solution:

- "ready for test" and "low priority" should be green to indicate no major problem.
- "high priority", "bug", "blocked" should be red to indicate a problem.

Note:

- Feel free to look for any solution that would make sence, rather than using random colors as we do now.

![image](https://user-images.githubusercontent.com/98878781/154080600-a30dcd11-fb01-47d1-89aa-89b53843549f.png)

**Comment by lazarmitic** [comment]
I agree, if you want to, feel free to edit colors of the labels :D

**Comment by Olafkuusik** [comment]
Changed colors to:
#B60205 - high priority
#EE3F46 - bug
#F45D43 - blocked
#FBCA04 - medium priority
#FAD8C7 - cannot reproduce
#1D76DB - optimization, enhancement
#B5308E - tech debt
#BFD4F2 - additional work, spike
#FFC274 - design, UX related, copy
#CC317C - feedback, question, user reported
#FAD8C7 - ready to test
#B2E5FC - low priority
#FFF2C0 - legal, documentation
#00887A - infrastructure
#CFD3D7 - invalid, non-issues, duplicates

explanation: categorize by severity and type. Tried to use more pleasant colors: greys-blues-yellows-reds
