### ISSUE TITLE
Add Sherlock to Home page 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#1040]
Under the security, section add an additional logo and link to the Sherlock report.

As we will have 5 cards perhaps we have two rows, first row of 3 and second of 2

<img width="1057" alt="Screenshot 2022-02-15 at 16 58 05" src="https://user-images.githubusercontent.com/17698024/154110689-511b83db-77c6-4fca-82d7-808efd0a3638.png">

Awaiting assets from @Olafkuusik

**Comment by RTP2016** [comment]
Also update the Immunefi bounty to $1,000,000

**Comment by ShawTim** [comment]
https://github.com/tempus-finance/tempus-website/pull/30
close this with this PR
