### ISSUE TITLE
Approve button on withdrawal active with null value in input box

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#1043]
Steps 
1. Go to the pool page 
2. Withdraw
3. Issue: I am able to approve 0.00 amount for withdrawal

This does not make sense to allow a user to approve zero amounts

Expected behaviour: 
DIsable the approve button when there is zero or null in the 'FROM' input boxes

<img width="639" alt="Screenshot 2022-02-16 at 09 29 05" src="https://user-images.githubusercontent.com/17698024/154236271-a5312619-9a29-4a89-a9eb-60bcba2274e4.png">

**Comment by irinelT** [comment]
This issue is still reproducible.

![image](https://user-images.githubusercontent.com/98878781/156155090-d8cfbede-a817-47aa-9f7c-00b2a8fca118.png)

**Comment by irinelT** [comment]
This is fixed.
