### ISSUE TITLE
Block range for fetched events when calculating swap fees is wrong

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1050]
This bug only reflects to older pools, if pool is less then 7 days old calculations are correct.

**Comment by irinelT** [comment]
@lazarmitic Any suggestion on how to test this?

**Comment by lazarmitic** [comment]
This change affects Variable APR (Tempus Fees part) shown on the dashboard. I'm not sure what's the best way to verify if the value shown is correct.

These kinds of things need to be tested with the script, because in order to check it we need data from the blockchain that script can fetch and utilize.

**Comment by irinelT** [comment]
This will be moved to next release as it cannot be tested now.

**Comment by irinelT** [comment]
We only support fixed income in since V3.
