### ISSUE TITLE
Missing layout elements in "Swap" section

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1058]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand DAI (or any other).
3. Manage.
4. Swap.
5. Pick Capitals in "From" dropdown
6. Set "From" amount to MAX.
7. Inspect the layout.

Expected:

- There is a token icon next to "Capitals"
- There is a token icon next to "Yields"
- There is a USD equivalent under the amount entered.

(it should be similar to Deposit section)
![image](https://user-images.githubusercontent.com/98878781/154673209-2687c618-eced-4cc3-bfd4-67c97da213a2.png)

Actual:
- There is no token icon next to "Capitals"
- There is no token icon next to "Yields"
- There is no USD equivalent under the amount entered.

![image](https://user-images.githubusercontent.com/98878781/154672514-f6689b02-2a8a-4a04-b17e-becacd8153a3.png)

**Comment by ShawTim** [comment]
@irinelT this should be an expected behavior:
- Capital token and Yield token are minted by Tempus, not publicly traded and wont have a USD value
- Neither Capital token nor Yield token have a token icon

**Comment by irinelT** [comment]
Ok, thanks for clarification. Closing the issue as it works as designed.
