### ISSUE TITLE
Confusing labels for Balance/Deposit

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1062]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand DAI.
3. Manage.
4. Deposit.
5. Pick DAI from "From" dropdown.
6. Inspect the label for the aset that is available to deposit.

Expected:
The label should be "Available to deposit" like on Dashbord.

Actual:
Label "Balance" is used for both MetaMask balance and Pool balnce which makes it confusing.

![image](https://user-images.githubusercontent.com/98878781/154818044-7e2c9e68-f50f-4edc-a35d-4388b333271e.png)

**Comment by Olafkuusik** [comment]
I agree with the proposal to change the label in the Transaction view to 'Available to deposit'.
![image](https://user-images.githubusercontent.com/22838368/155320915-33452689-b5c4-4b84-ad3c-8224e1a5ea4b.png)

**Comment by lazarmitic** [comment]
Should we change Balance to Avaialble to deposit on Mint page as well?

**Comment by Olafkuusik** [comment]
> Should we change Balance to Avaialble to deposit on Mint page as well?

Available to deposit for Mint transaction as well

**Comment by ShawTim** [comment]
so change label from `Balance` to `Available to Deposit` on Mint page and Deposit page (only)

**Comment by irinelT** [comment]
This is done.
