### ISSUE TITLE
Incorrect value for "Available to Deposit" on Dashboard

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1063]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Inspect the "Available to deposit" amount for DAI (or any other asset).

Expected:
It should match the value on "Deposit" screen.
The value on the "Deposit" screen matches MetaMask.

Actual:
Value on Dashbord is different than the value on Deposit screen.

![image](https://user-images.githubusercontent.com/98878781/154818204-5948c9ad-2f80-424d-98c4-68e20c3e4b87.png)

**Comment by danieledamiani** [comment]
The value `Available to Deposit` in the Dashboard is the sum of the values (in USD) of the available backing tokens (in this case DAI) and the yield bearing tokens (in this case yvDAI).

I've checked it and looks fine to me

**Comment by irinelT** [comment]
That makes sense.
