### ISSUE TITLE
Missing "Connect Wallet" button in an edge case

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1069]
Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Connect Wallet.
4. WalletConect.
4. Cancel (close window).

Expected:
- "Connect Wallet" button is displayed.

Actual:
- "Connect Wallet" button is not displayed until refresh.

![image](https://user-images.githubusercontent.com/98878781/154947253-690b82a5-7614-4817-83a8-b7c6cb67c05f.png)

**Comment by lazarmitic** [comment]
Following above reproductions steps I get MetaMask popup after I close WalletConnect QR code popup (this is another bug), if I close MetaMask popup as well I can see Connect Wallet button.

![Peek 2022-02-23 12-25](https://user-images.githubusercontent.com/7648077/155310641-ed8af72b-decb-4872-830a-6d77d18c5a77.gif)

**Comment by irinelT** [comment]
This is no longer reproducible.
