### ISSUE TITLE
Missing side bar on YFI

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1070]
Prerequisite:

- Connect MetaMask to Tempus App ([details](https://docs.tempus.finance/user-guides/how-to-connect-a-wallet))
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand YFI.
3. Manage.
4. Inspect the side bar on the right.

Expected:
There is a sidebar on the right just like on all other assets.

Actual:
The sidebar is missing.

![image](https://user-images.githubusercontent.com/98878781/155151860-419db75b-f2ea-4603-9033-1742c4450fe7.png)

**Comment by lazarmitic** [comment]
Sidebar on the right side (Current Position and Profit & Loss) only shows up after you have deposited.

**Comment by irinelT** [comment]
Yup. I see it. Thanks.
