### ISSUE TITLE
Ethereum network redirects the user to Fantom

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1071]
Steps:

1. Navigate to https://tempus.finance/
2. Click "INVEST NOW" on Ethereum network.
3. Inspect selected network.

Expected:
Ethereum network is selected.

Actual:
Fantom network is selected.

![image](https://user-images.githubusercontent.com/98878781/155171996-de5efb6b-8941-4aa8-9a48-16bc5a57fdb0.png)

**Comment by lazarmitic** [comment]
We actually never implemented this as an option :(

I will add it now :D

**Comment by lazarmitic** [comment]
Couple of notes here:

1st case - wallet not connected
1. You will get a popup to connect the wallet on app load.
2. You will be asked to change network in the wallet if it's not already set to correct one.

2nd case - wallet is connect with wrong network
1. You will get a popup to change network to correct one on app load.

3rd case - wallet is connected with correct network
1. App will open and show correct pools without any popups.

**Comment by lazarmitic** [comment]
So the solution to this is:

we removed network URL params when you click on invest now buttons on the homepage. This change is in production (homepage production).

**Comment by irinelT** [comment]
Good enough as a temporary solution.
