### ISSUE TITLE
Error in console `Error: Failed to get chain name from chain id '31337'`

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1072]
When I try to open app with unsupported network selected in the wallet I can see this error in the console.

1. Select any unsupported network in the wallet, in my case I selected AWS Tempus network that has chainId 31337.
2. Open app.tempus.finance
3. Check the console for errors
4. Error is in console

Expected:
App opens without any errors in the console and unsupported network UI is shown.

**Comment by irinelT** [comment]
@RTP2016 Could we use "The network your wallet is connected to is not currently supported by Tempus." instead of "The network your wallet is connected to doesn’t match the network selected here."

**Comment by RTP2016** [comment]
Yes, ser agree.

**Comment by irinelT** [comment]
**New requirement:** 
Change "The network your wallet is connected to is not currently supported by Tempus." instead of "The network your wallet is connected to doesn’t match the network selected here."

**Comment by lazarmitic** [comment]
Waiting for translations.

**Comment by lazarmitic** [comment]
Translations received:

IT: Il network al quale il tuo wallet è collegato non è supportato da Tempus al momento.
ES: La red a la que está conectada su billetera no es compatible con Tempus en este momento.

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/157433694-dd75a4c5-8b4b-4794-b23c-ca4abc6b1b0b.png)
