### ISSUE TITLE
add pattern check for percentage input

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1079]
**Describe the bug**
there is a percentage input box on "Slippage"
we should do sth similar to #1061 to stop user to input invalid numbers

**To Reproduce**
1. Go to any page
2. Click on "settings" on the top of the header
3. Change the Slippage to `1.45.67`

**Expected behavior**
You should not be able to input `1.45.67`, it should give you `1.45` or anything that make senses

**Actual behavior**
You can input `1.45.67`, but since it's not a valid number at the end your input become `0`

**Screenshots**
![image](https://user-images.githubusercontent.com/85455/155391484-35d1aace-6245-4f23-9115-7ddc204db445.png)

**Environment**
Operating System: any
Browser: any
Wallet: any
Network: any
URL: https://tempus-app-testnet-v2.web.app/

**Comment by irinelT** [comment]
I believe only 2 digits are memorised for slippage. In that case the number of decimals that the user can type in should be also 2, not infinite like it is now.

![image](https://user-images.githubusercontent.com/98878781/155755411-88a52960-5b10-4353-afcd-ec7ba06c7638.png)

**Comment by ShawTim** [comment]
this should be fixed in the next deployment
