### ISSUE TITLE
Remove Future Yield from fees tooltip

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1083]
Fees tooltip inside Pool card contains Future Yield row, it's not really clear to users what it represents so we should remove it.

**Comment by irinelT** [comment]
"Future Yield" row is not available. Closing the ticket.

![image](https://user-images.githubusercontent.com/98878781/156025239-53b8bdf4-d49f-4e29-899b-e87581d4bdc2.png)
