### ISSUE TITLE
Issue on Lido ETH pool: Max button not working, Available to deposit value not showing and execute button not enabled

### ISSUE THREAD

**Issue by Olafkuusik** [tempus-finance/tempus-app#1085]
All 3 of those issues happened together.
Video of the issue: https://www.loom.com/share/46d064bf748e4bec980f1a4bf19e6a86

**Comment by irinelT** [comment]
- Max button is fixed.
- Available to deposit is fixed.
- Execute is not testable on Ethereum network.

![image](https://user-images.githubusercontent.com/98878781/155531382-e9d2fc11-37eb-4bc7-8cda-5b46bc29f401.png)
