### ISSUE TITLE
Transaction sidemenu update

### ISSUE THREAD

**Issue by Olafkuusik** [tempus-finance/tempus-app#1088]
Changes proposed:

1. Add to the top left "< All pools"
2. Updated visual of the Pool's name / protocol + logos  (40px +20px)
3. Added "Contract addresses" to the bottom of the side-menu which shows all related etherscan hyperlinks (on click opens Etherscan link in a new tab) and a copy button-icon which copies the address only.
4. Possibility to add our footer/terms & conditions links to the bottom of sidemenu @RTP2016 (which if any would be like to add there?)
5. overflow from the sidemenu for the selected transaction type indicator (blue gradient rectangle with rounded right edge) //Can be omitted

![image](https://user-images.githubusercontent.com/22838368/155531264-1b64cc22-cf04-4ab6-b0bd-f9f419e46f46.png)

**Comment by lazarmitic** [comment]
I created separate issues tasks listed above:

1. [Add `< All Pools` navigation item in sidebar](https://github.com/tempus-finance/tempus-app/issues/1091)
2. [Update pool info style in sidebar](https://github.com/tempus-finance/tempus-app/issues/1092)
3. [Add contract addresses in bottom part of sidebar](https://github.com/tempus-finance/tempus-app/issues/1093)
4. I will skip this one until we get more info on it.
5. [Update style of sidebar selected item](https://github.com/tempus-finance/tempus-app/issues/1094)

**Comment by RTP2016** [comment]
In the sidebar footer we can have: 
Terms & Conditions >> https://tempus.finance/terms-of-service
Gitbook >> https://docs.tempus.finance/

**Comment by lazarmitic** [comment]
I updated above list of issues. Closing this task.
