### ISSUE TITLE
Add `< All Pools` navigation item in sidebar

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1091]
In top left corner we should add `< All Pools` clickable label that navigates user back to dashboard.

Screenshot of the desing:
![image](https://user-images.githubusercontent.com/7648077/155683730-5d8f6be4-5458-44aa-ac0b-f992d034c83c.png)

Design [link](https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus---Product?node-id=3739%3A27136).

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/156155478-07989772-5684-4f99-a185-35655ce559d9.png)
