### ISSUE TITLE
Add contract addresses in bottom part of sidebar

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1093]
We should add a `Contract Addresses` label in bottom part of sidebar that opens a tooltip on click. Tooltip should contain a list of addresses related to the pool. When user clicks on the address in the tooltip we should open that address on Etherscan/FTMScan in new tab. Clicking on copy icon next to the address should copy address in the clipboard.

Screenshot:
![image](https://user-images.githubusercontent.com/7648077/155685933-e902c811-68be-4958-8388-dc51ae095c54.png)

Design [link](https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus---Product?node-id=3739%3A27136).

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/156834447-1c247d09-65d2-4156-b196-81ab0a8d84c8.png)
