### ISSUE TITLE
Update style of sidebar selected item

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1094]
Selected item highlight element should overflow on the right side of sidebar.

Screenshot:
![image](https://user-images.githubusercontent.com/7648077/155686306-cb19173d-42a4-40f0-a3b5-4334d1dd20a4.png)

Design [link](https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus---Product?node-id=3739%3A27136).

**Comment by irinelT** [comment]
Selected item needs to be longer.

![image](https://user-images.githubusercontent.com/98878781/156164571-f9f248eb-5aac-46b5-b27a-58c9a3bb4aeb.png)

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/156574884-c6a568a0-4dde-4285-bb1f-a76a48e5403c.png)

**Comment by irinelT** [comment]
This is fixed.
