### ISSUE TITLE
Add links to GitBook and Terms and Conditions in bottom part of sidebar

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1096]
Screenshot:
![image](https://user-images.githubusercontent.com/7648077/155694482-03b2abad-48c7-42b7-a449-9530e3839ca8.png)

Design [link](https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus---Product?node-id=3739%3A27136).

**Comment by irinelT** [comment]
This is done.
