### ISSUE TITLE
Missing USDC when switching to Ethereum network

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1097]
**Describe the bug**
Missing USDC row when switching to Ethereum network from Fantom network. USDC is displayed after refresh.

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-testnet-v2.web.app/).
2. Switch to Ethereum network.
3. Approve in MetaMask.
4. Inspect the pool list.

**Expected behavior**
There should be USDC listed.

**Actual behavior**
USDC is not listed until refresh.

**Screenshots**
![Switch network](https://user-images.githubusercontent.com/98878781/155710914-b9c9e73e-6422-4766-b26c-c4627f05abf6.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom

**Additional context**

**Comment by lazarmitic** [comment]
If you don't have any balance in Ethereum USDC/Rari pool, it shouldn't be visible at all.

**Comment by irinelT** [comment]
I don't have neither USDC nor ETH, but they both show up after refresh.

**Comment by danieledamiani** [comment]
After some tests, I've found that Rari pool shows up either `principals` or `yields` values are positive. 

In my case the value left was very low (principals 0.000000124073404692), (yields 0.00000252431088309), dust from my previous interactions with the pool, even if the rounded shown value in Balance is 0.

To fix it we should allow some balance threshold, below that we hide the pool.

**Comment by RTP2016** [comment]
As discussed with the team. The Rari pool only shows when there is dust in the pool. No deposits are able to be made so limited risk for user.
