### ISSUE TITLE
Hide Variable APR Column 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#1112]
**Describe the bug**
We would like to remove the `variable yield` column on the dashboard view as a user test. 

**Expected behaviour**
As a user
I want to view only the fixed yields on the dashboard 
So I am not confused with 2 different options

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/156574101-9a8c4b3a-19de-4d97-b8b8-7ffde5a71d49.png)
