### ISSUE TITLE
when you have a position in the pool, pool page UI breaks

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1119]
**Describe the bug**
as title

**To Reproduce**
1. Go to https://tempus-app-testnet-v2.web.app/
1. Connect a network and select a pool that have deposit
1. see the screenshot

**Expected behavior**
UI wont break

**Actual behavior**
UI breaks

**Screenshots**
![image](https://user-images.githubusercontent.com/85455/156742857-135e2873-1d43-45a6-afa5-c8eb0acc0305.png)

**Environment**
Operating System: all
Browser: all
Wallet: any wallets that have a position in the pool
Network: any network but prefer fantom becoz of the gas gee
URL: https://tempus-app-testnet-v2.web.app/

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/157432870-ee3c3f59-2cec-479c-8d55-8b6e86fbe0be.png)
