### ISSUE TITLE
Matured pools in dashboard

### ISSUE THREAD

**Issue by Olafkuusik** [tempus-finance/tempus-app#1127]
Dashboard - child rows require a matured status. There are 2 cases: 
1. user has assets in the matured pool 
(withdrawal is enabled,  APR is not shown, assets in pools/available are shown, TVL is shown).
Withdrawal button leads to Transactions view - Withdrawal with all other transaction types disabled.

2. user has no assets in the matured pool (withdrawal is disabled, APR is not shown, TVL is shown)

We are not hiding the matured pools because the remaining TVL of a pool needs to add up at parent row level and we are showing all matured pools indefinitely but the logic might change for V3 where we will likely introduce filtering based on status.

![image](https://user-images.githubusercontent.com/22838368/157012340-7534a56f-57e6-41ea-a43f-b45662ac8014.png)

**Comment by lazarmitic** [comment]
Separate issues for tasks in this issue were created:

1. https://github.com/tempus-finance/tempus-app/issues/1179
2. https://github.com/tempus-finance/tempus-app/issues/1185
3. https://github.com/tempus-finance/tempus-app/issues/1189
4. https://github.com/tempus-finance/tempus-app/issues/1177
5. https://github.com/tempus-finance/tempus-app/issues/1192

Closing this one.
