### ISSUE TITLE
Execute button text `In Esecuzione` does not fit into single line

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1133]
**Describe the bug**
When `Executing` text is translated to Italian (In Esecuzione) it does not fit into single line, it goes to second line.

**To Reproduce**
1. Open any pool management page.
2. Change language from English to Italian.
3. Go to any action (swap for example).
4. Execute the action.

**Expected behavior**
Text inside execute button 'In Esecuzione' should be shown in a single line.

**Actual behavior**
Text inside execute button 'In Esecuzione' is shown in two lines.

**Screenshots**
![In Esecuzione text two lines bug](https://user-images.githubusercontent.com/7648077/157249656-52bb6fc6-73a0-4fb3-a090-d7da98b58510.gif)

**Environment**
Operating System: any
Browser: any
Wallet: any
Network: any
URL: any

**Additional context**
In order to solve this problem we should make Execute button wider. To keep Approve button width consistent with Execute button width we should update Approve button width to be same as Execute button width.

**Comment by irinelT** [comment]
Please correct "Approve" button too. Italian version "In Approvazione" does not fit in 1 line.

![image](https://user-images.githubusercontent.com/98878781/162033931-5e594cca-185d-492c-a481-fdda28fe2712.png)

**Comment by danieledamiani** [comment]
We could shorten them with `Approvazione` and `Esecuzione`

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/162790192-61c60526-a8a7-46ad-8cc1-89d99ec9843d.png)
