### ISSUE TITLE
Deposit fails with error 'Amount exceeds allowance'

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1139]
**Describe the bug**
When I try to deposit, approve button says approved but when I try to execute I get error message that says that amount I want to deposit exceeds allowance.

**To Reproduce**
1. Open any pool.
2. Go to deposit section.
3. Select backing token.
4. Enter 1 for the amount.
5. Click approve. (if not already approved).
6. Refresh the page.
7. Open deposit again.
8. Enter 2 for the amount.

**Expected behavior**
I expect approve button to be enabled because I only have one token approved and I'm trying to deposit two tokens.

**Actual behavior**
Approve button says approved like I already have two tokens approved, but that's not true.

**Screenshots**
![deposit-failed-allowance-not-correct](https://user-images.githubusercontent.com/7648077/157383716-a20db86c-ddee-4ecb-98e5-e4c0b58b243a.gif)

**Environment**
Operating System: any
Browser: any
Wallet: any
Network: any
URL: https://testnet-v2.tempus.finance

**Additional context**
This happens because of incorrect comparison between current allowance and amount user wants to deposit.

**Comment by irinelT** [comment]
This is fixed.
