### ISSUE TITLE
I cannot enter amount larger then 1000 when trying to deposit

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1141]
**Describe the bug**
Input fields for currency amount input does not allow users to enter value larger then 1000.

**To Reproduce**
1. Open any pool.
2. Go to deposit section.
3. Select token.
4. Try to enter amount larger then 1000.

**Expected behavior**
I should be able to enter any value.

**Actual behavior**
I'm not able to enter value larger then 1000.

**Screenshots**
![Peek 2022-03-09 07-44](https://user-images.githubusercontent.com/7648077/157387147-568e8594-94a1-44de-8d9c-ded71b397477.gif)

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: https://testnet-v2.tempus.finance/

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/157416365-61279904-85f3-49fa-b8aa-e50687dbef9d.png)
