### ISSUE TITLE
Provide additional info while waiting for MetaMask confirmation

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1144]
**Description**
Spinning circle does not provide enough information to the user about what is happening and what the user needs to do.

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-testnet-v2.web.app/).
2. Connect Wallet

**Expected behavior**
The message "Waiting for MetaMask approval" is displayed next to the spinning circle.

**Actual behavior**
No message is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/157419276-cc84b65f-4985-4202-a5fa-80be7d736e0d.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: none
Network: none
URL: https://tempus-app-testnet-v2.web.app/

**Additional context**

**Comment by RTP2016** [comment]
Good point! This is addressed in the ui refresh.
