### ISSUE TITLE
shorten address in contract addr tooltip should be longer

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1150]
![image](https://user-images.githubusercontent.com/85455/157520778-8db654c0-e810-4b8a-8676-08300b5c97cd.png)
see attached. there are plenty of places to put a `0x0000...0000` address here

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/157648824-9eb1d976-7e96-4c19-9a1a-212b00945b17.png)
