### ISSUE TITLE
In the dashboard 'Up to' text inside APR column is not translated

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1157]
**Describe the bug**
Text `Up to` that is part of APR column cells is not translated.

**To Reproduce**
1. Open dashboard.
2. Change language to Italian or Spanish.
3. Inspect Fixed APR column cells.

**Expected behavior**
Text `Up to` should be translated.

**Actual behavior**
Text `Up to` is not translated.

**Screenshots**
![up-to-not-translated](https://user-images.githubusercontent.com/7648077/157821560-e27532b2-88ba-464e-8595-4538fad90c87.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: https://testnet-v2.tempus.finance/

**Comment by lazarmitic** [comment]
Waiting for translations...

**Comment by lazarmitic** [comment]
Translations provided:

Italian: Fino a
Espanol: Hasta

**Comment by irinelT** [comment]
This is fixed.
