### ISSUE TITLE
Remove APR Graph from dashboard Fixed APR and Variable APR cells

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1158]
Description:
Small 'signal chart' that's visible next to APR values in the dashboard should be removed.

Screenshot:
![remove-apy-graph](https://user-images.githubusercontent.com/7648077/157822514-5ef835ca-ba4b-493d-a90d-56ea6c804fc7.gif)

**Comment by irinelT** [comment]
This issue is back.

**Comment by lazarmitic** [comment]
This is done in 2.2 as you can see, and current version we are testing is 2.1.3. So it's expected that something from 2.2 is not part of 2.1.3

**Comment by irinelT** [comment]
Understood.
Closing the ticket.
