### ISSUE TITLE
Remove APR value color coding in dashboard

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1160]
Description:
Inside Dashboard Fixed and Variable APR column values are shown in orange color if value is above 20%. We want to remove this color coding and always display APR values with black text.

Screenshot:
![orange-apr-text](https://user-images.githubusercontent.com/7648077/157826685-ec68e83f-e414-4601-9678-479bfaa0e610.gif)

**Comment by irinelT** [comment]
This can be tested on Ethereum Fork by Swapping Capitals for Yields which will increase APR over 20%.

**Comment by irinelT** [comment]
This is Done.

![image](https://user-images.githubusercontent.com/98878781/160121058-f992cfad-fbe8-4bce-849e-57d82fd86163.png)
