### ISSUE TITLE
Update community dropdown to match the design

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1168]
Community dropdown in header of the app does not match the design in terms of spacing (padding/margins). We should update the app to match the design.

Design [link](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus---Design-System?node-id=32%3A479).

**Comment by irinelT** [comment]
Done.

![image](https://user-images.githubusercontent.com/98878781/158236817-5c982c35-fa66-4dd0-8176-1c5a9ef10622.png)
