### ISSUE TITLE
Add 'since' label to Profit & Loss chart tooltip date

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1170]
In the design files there is a 'since' label before date in profit and loss chart tooltip, we should add it to the app as well.

See the tooltip in this screenshot from design:
![image](https://user-images.githubusercontent.com/7648077/158141867-320793a2-6a17-4dde-8998-2497de4cfc84.png)

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/158235783-5f402582-a1ed-41e9-9d2c-6157aa2f2ce4.png)

@lazarmitic Will additional elements be added later?

- Month should be a number.
- Min value.
- Max value.

**Comment by lazarmitic** [comment]
Yes, other things will be added as separate tasks.
