### ISSUE TITLE
Withdraw after maturity should force user to withdraw everything

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1176]
After pool matures, user can withdraw tokens in any ratio and there are no swaps under the hood so this makes withdrawal in any ratio pretty efficient.

Also there is no need to leave any tokens/assets in matured pools because they are no longer generating any profits.

Because of the above two points we should disable token amount inputs in withdraw and force user to withdraw everything. We can do this by pre-filling all token input fields with maximum amounts, disable those fields to prevent user adjusting the amounts, and only allow user to approve and execute the transaction.

**Comment by RTP2016** [comment]
This makes sense as we shouldn't really have remnant deposits in a pool after maturity.

**Comment by irinelT** [comment]
This is fixed.
