### ISSUE TITLE
Change 'Manage' to 'Withdraw' for matured pools

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1179]
Child rows in the dashboard have 'Manage' button that opens the pool. For matured pools we want to:

1. If user has balance in matured pool, 'Manage' button should be changed to 'Withdraw'
2. If user does not have balance in matured pool, 'Manage' button should be disabled (it still says 'Manage' but disabled).

Design [link](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus---Design-System?node-id=495%3A9421).

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/159267661-db5ca3b1-668d-496f-b156-97174be48fad.png)
