### ISSUE TITLE
localization for date format

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1181]
when we switch locale, besides the date format should be localized as well.

ideally, currency format (but we only support USD for now) and UI (left to right, right to left, element width, etc) needs to be localized.

**Comment by irinelT** [comment]
This has no implications on UI at this time.

**Comment by ShawTim** [comment]
> This has no implications on UI at this time.

you can verify anything about the date (e.g. xx days left) when switching locale to verify this
