### ISSUE TITLE
Maturity column in dashboard should show 'Matured' label for matured pools

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1185]
When pool is mature, instead of showing 'Time to maturity' we should show a label that reads 'Matured'.

Design [link](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus---Design-System?node-id=495%3A9421).

Screenshot for reference:
![image](https://user-images.githubusercontent.com/7648077/158379585-3e241998-f2fc-4339-9c5a-95bff445f7b7.png)

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/159269066-b107094c-2179-423f-b721-a94923215680.png)
