### ISSUE TITLE
Hide APR values in the dashboard if pool is matured

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1189]
Once pool is mature, instead of showing APR values in the dashboard we should show a dash `-`.

Design [link](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus---Design-System?node-id=495%3A9421).

**Comment by irinelT** [comment]
Endless loading is shown instead of a dash.

![image](https://user-images.githubusercontent.com/98878781/159253969-e4d4f081-2773-4b90-b435-18c205d850c1.png)

**Comment by irinelT** [comment]
This just got fixed.

![image](https://user-images.githubusercontent.com/98878781/159255279-53f48ba7-3ecf-483e-bf80-4806c2e4e9af.png)
