### ISSUE TITLE
After clicking 'Withdraw' on dashboard matured pool I'm presented with 'Deposit' screen that's disabled in sidebar

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1192]
**Describe the bug**
When I click 'Withdraw' button on the dashboard for matured pool, application opens Deposit screen even though it's disabled in sidebar and should not be available. After I try to enter some amount of tokens in deposit screen app crashes.

**To Reproduce**
1. Open the dashboard.
2. Click on 'Withdraw' for matured pool.
3. Select token on deposit screen.
4. Try to enter any amount for token input.

**Expected behavior**
After I click 'Withdraw' on dashboard for matured pool application should open Withdraw screen with all other options in sidebar disabled.

**Actual behavior**
Application opens Deposit screen when I click 'Withdraw' on dashboard for matured pool. And application crashes if I try to enter any amount of tokens in token input on the deposit screen.

**Screenshots**
![deposit-active-on-matured-pools](https://user-images.githubusercontent.com/7648077/158468666-e3457825-c58b-4d41-af10-22747a4ef986.gif)

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: localhost

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/159268204-4a18921f-4ac1-49ab-8798-f421272d040c.png)
