### ISSUE TITLE
Add support for Ethereum fork on AWS

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1201]
We have an Ethereum fork on AWS EC2, we should allow user to connect to this network using network selector in the app.

This network is only for testing/development purposes and it should not be visible in production environment.

**Comment by irinelT** [comment]
This is Done.

![image](https://user-images.githubusercontent.com/98878781/159255705-dbfd48c5-cda8-46ac-91a7-bdcf915cd81e.png)
