### ISSUE TITLE
Missing the "Approve" button

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1206]
**Description**

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).
2. Expand ETH pool.
3. Manage.
4. Deposit.
5. Pick ETH in "From" dropdown.

**Expected behavior**
There is an approve button.

**Actual behavior**
Approve button is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159000336-8f0f2ac3-9374-48bb-8e16-ed4e2f765a6f.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Tempus Ethereum Fork
URL: https://tempus-app-stage.web.app/

**Additional context**

**Comment by lazarmitic** [comment]
ETH is a native token that doest not need approval.

**Comment by lazarmitic** [comment]
ETH is a native token that doest not need approval.

**Comment by lazarmitic** [comment]
Make sure to add ticket to tempus project and set correct state

**Comment by irinelT** [comment]
Ah, yes. I agree. Closing the ticket.
