### ISSUE TITLE
No pools available when MetaMask is not installed

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1207]
**Description**
All pools should be listed when the wallet is not installed.

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).

**Expected behavior**
All pools are listed.

**Actual behavior**
There are no pools.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159000882-5d2a6350-ac6e-4f5b-8cef-e313da1d2e23.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: None
Network: None
URL: https://tempus-app-stage.web.app/

**Additional context**

**Comment by lazarmitic** [comment]
I'm not able to reproduce this issue:

![image](https://user-images.githubusercontent.com/7648077/159001986-8a826823-27fa-4c94-963f-d39737e8ada9.png)

I tried on stage URL: https://tempus-app-stage.web.app/

Do you have any errors in the console?
