### ISSUE TITLE
Fiat label is not covered by the modal backdrop

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1210]
**Describe the bug**
The "Fiat" label on the switcher is not covered by the backdrop of the network selection modal dialog. 

**To Reproduce**
1. Navigate to the [test environment](https://tempus-app-stage.web.app/).
2. Open the network selection dialog.

**Expected behavior**
The "Fiat" label on the switcher should be below the modal's backdrop.

**Actual behavior**
The label is on the same level as the modal backdrop and thus, clickable.

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8989109/159040318-b1c1d0fd-4da9-45e6-9f85-72ac80fdbf5f.png">

**Environment**
Operating System: macOS 12.2.1
Browser: Brave 1.36.109
Wallet: N/A
Network: N/A
URL: [tempus-app-stage.web.app](https://tempus-app-stage.web.app/)

**Comment by irinelT** [comment]
This is good.

![image](https://user-images.githubusercontent.com/98878781/159255997-1186a22f-26c5-4e63-a0ae-c5d2bd212c77.png)
