### ISSUE TITLE
If withdraw fails for matured pool, user is sent to Deposit page

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1215]
**Describe the bug**
If pool is matured and withdraw fails, application navigates to Deposit screen.

**To Reproduce**
1. Open any matured pool.
2. Try to withdraw.
3. Withdraw fails (maybe).

**Expected behavior**
Application should stay on Withdraw screen.

**Actual behavior**
Application navigates to Deposit screen.

**Screenshots**
![navigate-to-deposit-error](https://user-images.githubusercontent.com/7648077/159238402-63c1ae42-e52f-4130-baa6-9fbf84c88374.gif)

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: local environment

**Additional context**
If withdraw fails we should not navigate to Deposit screen even if pool is not matured.

**Comment by irinelT** [comment]
This is fixed.
