### ISSUE TITLE
Withdraw fails for matured pools

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1217]
**Describe the bug**
If I try to withdraw from matured pool I get an error.

**To Reproduce**
1. Open any matured pool.
2. Try to withdraw.

**Expected behavior**
Withdrawal should be successful.

**Actual behavior**
Withdrawal fails.

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: local

**Additional context**
Error that I get is `Error: VM Exception while processing transaction: reverted with reason string 'BAL#004'`.

**Comment by lazarmitic** [comment]
Waiting for new pools to mature in order to test this one.

**Comment by irinelT** [comment]
This issue is still reproducible. Backend is working on it.

**Comment by irinelT** [comment]
This is fixed.
