### ISSUE TITLE
Fixed APR not loading for matured pools

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1218]
**Describe the bug**
If pool is mature fixed APR is not loading on the dashboard.

**To Reproduce**
1. Open dashboard.
2. Inspect Fixed APR column for matured pools.

**Expected behavior**
Fixed APR should not be visible for matured pools, I should see `-` instead of Fixed APR value.

**Actual behavior**
I can see loading circle instead of `-`.

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: local

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/159255358-409c94be-10d2-42ee-bfd5-35bd1e98ce87.png)
