### ISSUE TITLE
User gets redirected to Deposit screen after withdraw for matured pools

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1220]
**Describe the bug**
When pool is mature and user withdraws his position from the pool he is redirected to deposit screen.

**To Reproduce**
1. Open any matured pool.
2. Withdraw from the pool.

**Expected behavior**
Application should not navigate to Deposit screen if pool is matured. It should say on Withdraw screen.

**Actual behavior**
Application navigates to Deposit screen.

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: local

**Comment by irinelT** [comment]
This is fixed.
