### ISSUE TITLE
Slippage value is lost after refresh

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1226]
**Description**
Value of slippage is returned to 1% after the user changes it.

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).
2. Open Settings dropdown.
3. Set slippage value to 55%.
4. Refresh the page.
5. Inspect slippage value

**Expected behavior**
Slippage should be 55%.

**Actual behavior**
Slippage is 1%.

**Screenshots**
![slippage](https://user-images.githubusercontent.com/98878781/159344024-ccf8032f-2326-4863-b48d-1e49c48ed8e4.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: https://tempus-app-stage.web.app/

**Additional context**

**Comment by lazarmitic** [comment]
This is expected behavior. We are not storing slippage value anywhere.

**Comment by irinelT** [comment]
Ok, we will implement it later.
Adding @RTP2016 for help with deciding if/when this should be implemented.
