### ISSUE TITLE
Deposit fails constantly

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1227]
**Description**
The user cannot deposit funds.

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).
2. Manage.
3. Deposit.
4. Insert deposit amount 99 ETH.
5. Approve.
6. Execute.

**Expected behavior**
Transaction is successful.

**Actual behavior**
Transaction failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159346165-fea8eacd-425c-4738-a683-0699922cce12.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: https://tempus-app-stage.web.app/

**Additional context**
Changing the slippage, pool or amount doesn't help. Deposit never works.

**Comment by lazarmitic** [comment]
You need to restart metamask in order to make it work. Nonce in your metamask is too high. This happens when we restart forked network and your metamask is not restarted as well.

**Comment by irinelT** [comment]
This was not a Tempus-app issue.
It was resolved as described here: https://github.com/tempus-finance/tempus-frontend-wiki/wiki/Test-Automation#forked-network
