### ISSUE TITLE
"Available to Deposit" is incorrect

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1234]
**Description**
Available to deposit on Mint page is higher then my entire balance.

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).
2. Manage.
3. Mint.
4. Insert Mint amount 9999 ETH.
5. Inspect "Available to Deposit" amount.

**Expected behavior**
It should be equal to amount in the wallet.

**Actual behavior**
It is higher then wallet amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159552569-e845386e-c88c-4caf-95b3-5fe357255c39.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: https://tempus-app-stage.web.app/

**Additional context**
After refresh, this issue was fixed.

**Comment by lazarmitic** [comment]
I will move this to 2.2 because it's not related to matured pools and it's not a regression.

**Comment by RTP2016** [comment]
<img width="984" alt="Screenshot 2022-04-11 at 09 12 28" src="https://user-images.githubusercontent.com/17698024/162693481-db8fd1cc-12f9-4b55-ade5-d4f28c77f9de.png">
I don't see this being an issue @irinelT

**Comment by irinelT** [comment]
I cant reproduce it either. Closing the ticket.
