### ISSUE TITLE
"Time Remaining" should be updated without refresh

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1237]
**Description**
Time Remaining is incorrect because its not updated

**To Reproduce**
1. Navigate to [test environment](https://tempus-app-stage.web.app/).
2. Manage.
3.Inspect Time Remaining

**Expected behavior**
It should be updated every minute.

**Actual behavior**
It updates on page refresh.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159727315-70b9232c-d003-4d34-8708-b5490adce9fe.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: https://tempus-app-stage.web.app/

**Additional context**

**Comment by lazarmitic** [comment]
I will move this out of 2.1.1 because it's not really urgent.

**Comment by irinelT** [comment]
This is fixed.
