### ISSUE TITLE
"See openings" hyperlink should point to Tempus jobs

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1239]
**Description**
"See openings" hyperlink points to Tempus, not to Tempus jobs.

**To Reproduce**
1. Navigate to [test environment](https://stage-tempus.web.app/).
2. Scroll to bottom of the page.
3.Inspect Time Remaining

**Expected behavior**
https://angel.co/company/tempusfinance/jobs

**Actual behavior**
https://angel.co/company/tempusfinance

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/159749320-987af3fe-0a97-45ae-b9dc-d53a7261aa0a.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: NA
Network: NA
URL: https://stage-tempus.web.app/

**Additional context**

**Comment by ShawTim** [comment]
this should be `tempus-website`
