### ISSUE TITLE
Manage button on dashboard is not grayed out when disabled

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1252]
**Describe the bug**
When pool is mature and manage button is disabled user is not able to click on the button and that's expected, but the style of the button is not correct, it looks like it's enabled but it should be grayed out.

**To Reproduce**
1. Open dashboard.
2. Expand parent row that has matured pools.
3. Inspect Manage button for mature pool.

**Expected behavior**
If user does not have any balance in the pool manage button should be grayed out.

**Actual behavior**
User does not have any balance in the pool, manage button is disabled, but it's not grayed out.

**Screenshots**
![manage-button-disabled-style](https://user-images.githubusercontent.com/7648077/160015156-7e83b09f-761f-4cd4-b08c-ed486326fdc2.gif)

**Environment**
Operating System: Ubuntu 20.04
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: local

**Additional context**
Here is the design for disabled Manage button: [link](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System?node-id=79%3A550)

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/161997081-d22e393a-1bc4-4ef1-843c-2e3f952c15a9.png)
