### ISSUE TITLE
Atomic v3 component: Typography

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1261]
![image](https://user-images.githubusercontent.com/85455/160373840-63a05b52-791b-4f2d-a5bd-0b7ca8a854dc.png)

https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=10%3A8118

**Comment by irinelT** [comment]
Correct font is used.


![Image](https://user-images.githubusercontent.com/98878781/184341397-0d000a2f-8f43-4ccb-b8aa-948da1d01bda.png)
