### ISSUE TITLE
Atomic v3 component: Iconography

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1262]
![image](https://user-images.githubusercontent.com/85455/160452053-318972e8-d86c-4e5f-8741-4c1ed224f026.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=18%3A5866

only those "Icons in use"

**Comment by irinelT** [comment]
![Image](https://user-images.githubusercontent.com/98878781/184322816-4db3c146-7cd8-4109-91d2-7b56719b451d.png)
