### ISSUE TITLE
Molecular v3 component:  switch view button (with icon)

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1264]
![image](https://user-images.githubusercontent.com/85455/160374704-1f2046b2-9515-4887-8d32-0475eaf7f4eb.png)

https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

grid view <-> list view

**Comment by irinelT** [comment]
@ShawTim Is this implemented in V3?

**Comment by lazarmitic** [comment]
No, we decided to skip table view for v3. Because of that we removed view selector.
