### ISSUE TITLE
Molecular v3 component: Wallet Button

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1265]
![image](https://user-images.githubusercontent.com/85455/160374704-1f2046b2-9515-4887-8d32-0475eaf7f4eb.png)

https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Wallet button looks fine.

![WalletButton](https://user-images.githubusercontent.com/98878781/175528538-534cc424-7152-4d13-8735-4eaa03294fed.PNG)
