### ISSUE TITLE
Molecular v3 component: Button for network/wallet switcher

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1266]
![image](https://user-images.githubusercontent.com/85455/160374704-1f2046b2-9515-4887-8d32-0475eaf7f4eb.png)

https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Looks good, exactly like in application.

![WalletSwitcher](https://user-images.githubusercontent.com/98878781/175775863-2391b1fe-fd52-475a-b4cc-0baadb338d4b.PNG)

![SelectNetworkSwitcher](https://user-images.githubusercontent.com/98878781/175775874-6d96d27d-bf5f-4e44-8a92-7d8c99e43775.png)
