### ISSUE TITLE
Molecular v3 component: Fiat/Token toggle

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1269]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Fiat/Token toggle is not implemented on V3.

![FiatTokenToggle](https://user-images.githubusercontent.com/98878781/183060843-5930bd25-4103-4131-b783-f2051bd43b1e.PNG)

**Comment by iamvukasin** [comment]
The toggle was removed from the designs. You can safely close the issue.

**Comment by irinelT** [comment]
This is out of scope.
