### ISSUE TITLE
Molecular v3 component: Slippage Input

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1273]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

maybe a variation of text input, ends with buttons

**Comment by irinelT** [comment]
Slippage Input looks on application looks good.

![SlippageInput](https://user-images.githubusercontent.com/98878781/175527062-8e8b854b-cf85-47b0-901f-56a7b2dd7cbe.PNG)
