### ISSUE TITLE
Molecular v3 component: dropdown with label as menu items

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1276]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
The design changed slightly and the implementation was done accordingly.


![Image](https://user-images.githubusercontent.com/98878781/184340929-d9973b27-1159-4d96-816c-50f8199e65fa.png)
