### ISSUE TITLE
Molecular v3 component: dropdown with checkbox as multiple select menu items

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1277]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
There is no multiple select menu.

https://user-images.githubusercontent.com/98878781/182880711-cb23c3b8-160b-4985-88fe-1649d30bc48e.mp4

**Comment by iamvukasin** [comment]
The component is not used anymore since we switched the Filter dropdown to use radio buttons instead.

**Comment by irinelT** [comment]
Closing the ticket.
This working as per new design.
