### ISSUE TITLE
Molecular v3 component: Currency Input

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1278]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
This looks good to me.

![CurrencyInput](https://user-images.githubusercontent.com/98878781/176884096-06aade38-befd-4c44-a14c-873f61d6ed51.PNG)
