### ISSUE TITLE
Molecular v3 component: Number input with max button

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1280]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Max button is missing, however the design matches with the design from Figma, so its okay. Number input with percentage buttons works fine as well.

https://user-images.githubusercontent.com/98878781/183072275-d50d8bf5-ae72-4dd9-83dc-038414cff4a2.mp4
