### ISSUE TITLE
Molecular v3 component: Term Tabs

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1281]
![image](https://user-images.githubusercontent.com/85455/160378540-c8d28392-1c5c-4290-8fa9-79ae6506935d.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
@iamvukasin Can you provide specific details? I am not sure what "Term tabs" refers to.

**Comment by iamvukasin** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/8989109/184381276-58b2d594-6b01-44b0-bb02-89156bfbc58e.png">

Right now, we don't have any pool that has multiple term dates, so you can try to test them [here](https://storybook.tempus.finance/?path=/story/termtabs--three-term-dates). It's the same code we use in the app, although isolated from the rest of the app.

**Comment by irinelT** [comment]
Looks good.
