### ISSUE TITLE
Organism v3 component: Header navbar

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1282]
![image](https://user-images.githubusercontent.com/85455/160393040-ceb8d2c1-b798-4f19-b321-76fd46d57555.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Community is missing from Header. From navSubHeader: Fixed, Busted and All are missing on the website.

https://user-images.githubusercontent.com/98878781/183440498-90778eaf-6ecd-4015-95cc-14f4ad3fd073.mp4

**Comment by lazarmitic** [comment]
In initial version we we only have Fixed pools, because of that we decided to remove Fixed/Boosted filter.

Community was removed intentionally from the header.
