### ISSUE TITLE
Organism v3 component: View Header with filtering options

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1283]
![image](https://user-images.githubusercontent.com/85455/160393040-ceb8d2c1-b798-4f19-b321-76fd46d57555.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Filtering options are working fine, however the design is different on the website, there are no list/grid buttons.

https://user-images.githubusercontent.com/98878781/183441288-831eb9f7-32c4-4a6d-8d91-28689a1c5f0c.mp4

**Comment by lazarmitic** [comment]
We decided to skip adding table view for initial version. It will be added later.
