### ISSUE TITLE
Organism v3 component: Page navigation tabs

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1284]
![image](https://user-images.githubusercontent.com/85455/160393040-ceb8d2c1-b798-4f19-b321-76fd46d57555.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

to be clear, it means Market/Profolio

**Comment by irinelT** [comment]
This looks fine, it matches with the design from Figma.
![PageNavigationTabs](https://user-images.githubusercontent.com/98878781/182837325-214c29c0-94c3-4d2c-a49d-5f21d1673f69.PNG)
