### ISSUE TITLE
Organism v3 component: View filtering options dropdown

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1285]
![image](https://user-images.githubusercontent.com/85455/160393040-ceb8d2c1-b798-4f19-b321-76fd46d57555.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by iamvukasin** [comment]
Duplicate
