### ISSUE TITLE
Organism v3 component: Settings popup

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1291]
![image](https://user-images.githubusercontent.com/85455/160395156-11f0cbe7-25c4-431f-88f0-e2a156b257cf.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Settings popup component looks good.

![SettingsComponents](https://user-images.githubusercontent.com/98878781/175380118-a8b652a0-422f-4fc8-90ca-61a3a3e6f074.PNG)
