### ISSUE TITLE
Organism v3 component: Fee Tooltip

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1292]
![image](https://user-images.githubusercontent.com/85455/160395278-83daed6d-2e0f-45c3-b8a2-7cdd69bef2eb.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
This looks fine.

![FeesAndTransactionInfo](https://user-images.githubusercontent.com/98878781/176884394-90db2cbd-9210-43ba-8b7d-fc0c99726521.png)
