### ISSUE TITLE
Organism v3 component: Wallet Popup

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1293]

**Comment by lazarmitic** [comment]
Wallet popup UI missing for v3 of the UI.

Should we use same UI for wallet popup we have in v2 of the app? Waiting for response from designers.

**Comment by lazarmitic** [comment]
Moving to blocked until @Olafkuusik gives us a green light that current wallet popup is ready for implementation.

**Comment by lazarmitic** [comment]
Design finalized and approved. We can start working on wallet popup.

**Comment by irinelT** [comment]
Wallet popup looking good.

![WalletPopUp](https://user-images.githubusercontent.com/98878781/182861761-665293bb-aa72-4441-854e-ad2724d8d4f9.PNG)
