### ISSUE TITLE
Organism v3 component: Network/Wallet switcher

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1294]
![image](https://user-images.githubusercontent.com/85455/160395787-d173e7ac-af3e-44b2-b016-dbeb1466ad97.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
This looks fine.

![SelectNetworkSwitcher](https://user-images.githubusercontent.com/98878781/176191064-45ebf12e-cebe-44f2-88a8-310557eb7a6e.png)

There are less option for choosing the wallets. Additional wallets will be added later.

![WalletSwitcher](https://user-images.githubusercontent.com/98878781/176191312-0ad3b3d4-ab5a-4c91-bfcc-513fce68cd21.PNG)
