### ISSUE TITLE
Organism v3 component: Deposit Modal

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1295]
![image](https://user-images.githubusercontent.com/85455/160395977-3fcff5d9-bf38-450e-9f04-352545664de8.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
The Deposit Modal matches with the one on Figma.

![DepositModal](https://user-images.githubusercontent.com/98878781/182836154-cadfa510-9728-43de-b593-f615528bbec1.PNG)
