### ISSUE TITLE
Organism v3 component: Withdraw Modal

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1296]
![image](https://user-images.githubusercontent.com/85455/160396087-c1718fcc-f134-4ece-b6db-a71b40995643.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Looks fine.

![WithdrawComponent](https://user-images.githubusercontent.com/98878781/175777025-878b1ffa-c5dc-42b1-9feb-bccea5ce2924.png)
