### ISSUE TITLE
Organism v3 component: XXXX Completed Modal

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1297]
![image](https://user-images.githubusercontent.com/85455/160396299-f9390e39-b0ba-43e5-b545-aa71ab245615.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
This looks good.

https://user-images.githubusercontent.com/98878781/182876653-41bc0129-a211-4493-b707-fd22891c3836.mp4
