### ISSUE TITLE
Organism v3 component: Deposit Preview Modal

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1298]
![image](https://user-images.githubusercontent.com/85455/160396512-a1a27e48-e109-4d39-bb49-9de788572609.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
The design on website matches with the design from Figma.
https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus%3A-Product---Web-V3?node-id=2903%3A39799
![MakeDeposit](https://user-images.githubusercontent.com/98878781/183059371-4709146e-013e-49f6-b01b-04034c87853e.PNG)
