### ISSUE TITLE
Organism v3 component: Chart Tooltips

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1300]
![image](https://user-images.githubusercontent.com/85455/160396870-812fad86-8577-41d4-9530-7bbbdd2d9bd5.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Is this it? Doesn't look as designed.

![Image](https://user-images.githubusercontent.com/98878781/185808493-dd9b6ffc-c48d-434c-ab95-fa98c8565fa8.png)

**Comment by iamvukasin** [comment]
Yes, it is. The design was changed: you can find it [here](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System---V3?node-id=2136%3A23783) (with the title though).

**Comment by irinelT** [comment]
I see. That is good. Closing the ticket.
