### ISSUE TITLE
Organism v3 component: Chart

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1301]
![image](https://user-images.githubusercontent.com/85455/160397089-d16c8bff-a542-46e2-91b1-9e2bdf27d582.png)
https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System-V3?node-id=28%3A691

**Comment by irinelT** [comment]
Chart background should be white, not green.
Chart should be green, not white.
![image](https://user-images.githubusercontent.com/98878781/184721449-c8bacb6a-7815-46cc-85ca-78b5f7deb338.png)

**Comment by iamvukasin** [comment]
Actually, the background is white and the chart area is semi-transparent turquoise, but, since values are negative, it looks inverted and strange. If you think of the chart area as an area between the chart line and the x-axis, you will understand that it is colored correctly.
