### ISSUE TITLE
If child row is not visible in dashboard do not include it in parent statistics

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1306]
For example:

First child row TVL: 400$
Second child row TVL: 200$ (not visible)

Parent TVL: it should be 400$ because second child is not visible to user.

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/160557948-bbe07daf-5680-4c6d-9a47-d338856f36d3.png)
