### ISSUE TITLE
The app breaks when typing in deposit value

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1320]
**Description**
-

**To Reproduce**
1. Navigate to Staging environment.
2. Expand WETH pool.
3. Manage.
4. Deposit.
5. Pick WETH in "From" dropdown.
6. Enter 1111111 value.

**Expected behavior**
User can type in any value.

**Actual behavior**
The app breaks.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/160602099-451651b3-532c-4af2-8397-690216b14343.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: Staging environment

**Additional context**
This happend before https://github.com/tempus-finance/tempus-app/issues/1205

**Comment by irinelT** [comment]
This happens again on big integer like 12121212121212121212121212.

![big_integer](https://user-images.githubusercontent.com/98878781/162287353-3ebb633c-4c79-45bd-bd8e-eecf99f68e86.gif)

**Comment by irinelT** [comment]
Original issue is fixed. A related issue is opened in #1414 .

**Comment by ShawTim** [comment]
reopen to revert the fix becoz it cause another issue

**Comment by irinelT** [comment]
Original issue is fixed.
