### ISSUE TITLE
Atomic v3 component: loading circle

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1331]
![image](https://user-images.githubusercontent.com/7648077/160773458-1893d430-b150-4ac5-8b36-910d27671efe.png)

Create a loading circle with animations.

**Comment by irinelT** [comment]
This looks well.

https://user-images.githubusercontent.com/98878781/182878008-1747332c-3cc0-4389-a12b-a1d02b057713.mp4
