### ISSUE TITLE
Atomic v3 component: Logos

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1344]
![image](https://user-images.githubusercontent.com/85455/161033958-6ac4b216-65eb-4417-97ca-cbe061ab92bf.png)

https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System---Version-%233?node-id=18%3A6187

**Comment by irinelT** [comment]
Not all are used but the ones that are used are correct.
