### ISSUE TITLE
Automatically switched to Deposit after Withdrawal

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1395]
**Description**
The user is redirected to Deposit after executing Withdraw.

**To Reproduce**
1. Navigate to Staging environment.
2. Expand DAI pool.
3. Manage.
4. Withdraw.
5. Enter 5 DAI amount.
6. Approve.
7. Execute.

**Expected behavior**
Withdraw section should be selected on the left nav.

**Actual behavior**
Deposit section is selected on the left nav.

**Screenshots**
![witdraw](https://user-images.githubusercontent.com/98878781/162281134-94b04d24-08b4-4aba-af65-3b046683cfec.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: ETH fork
URL: Staging environment

**Additional context**

**Comment by lazarmitic** [comment]
This is intended. User stays on withdraw screen only for mature pools.

**Comment by irinelT** [comment]
Working as designed, closing the ticket.
