### ISSUE TITLE
BaseInput should use the value used in setTimeout instead of ev.currentTarget.value

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1396]
the problem is `ev.currentTarget.value` only represent the current DOM attribute `value` which is possible not yet to be updated.
consider this scenario:
- textbox empty
- user type "abcd"
- user quit textbox within 300ms

in this case textbox should immediately update the `value` to "abcd" but since the current implementation use `ev.currentTarget.value` which is still empty when user quit.

**Comment by irinelT** [comment]
Works as expected.
