### ISSUE TITLE
Modal component

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1493]
Modal component should open up in the middle of the screen, it should have a backdrop that closes modal when clicked.

It should also have close button in top right corner.

**Comment by irinelT** [comment]
Modal component opens up in the middle of the screen, the modal component closes when you click on the screen. Also the modal component displays a close button in top right corner that works.

https://user-images.githubusercontent.com/98878781/175527694-dc73d02b-812e-4aa8-ba75-d31338c7c96b.mp4
