### ISSUE TITLE
Links within transaction history do not work

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1532]
**Describe the bug**
Links within transaction history do not work.

**To Reproduce**
1. Navigate to Staging environment
2. Expand one of the members of the "Transaction history"
3. Click on the link "View on Etherscan"
4. Inspect the Etherscan page

**Expected behavior** 
The page with information on Etherscan opens.

**Actual behavior**
A new tab with the following text opens: "This site can`t be reached"

**Screenshots**

![Bug](https://user-images.githubusercontent.com/98878781/166460621-2473e318-5d6d-4191-9e09-aef706124a65.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: Staging

**Additional context**

**Comment by danieledamiani** [comment]
`ethereum-fork` is our fork of ethereum, therefore Etherscan won't recognise the transaction link

**Comment by irinelT** [comment]
Links within "Transaction history" work for all networks except Ethereum fork network.
