### ISSUE TITLE
`Tooltip` arrow behave differently in different browser

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1540]
![image](https://user-images.githubusercontent.com/85455/166685017-5d852b1e-9928-460d-a109-c0de99ea3f26.png)
vs
![image](https://user-images.githubusercontent.com/85455/166685047-07c57aeb-6256-40ca-a8cf-78d81f6b8090.png)

**Comment by irinelT** [comment]
This looks good now:

Mozilla FF:

![ToolTipArrow](https://user-images.githubusercontent.com/98878781/175562147-c3d4e567-7893-45af-8cb7-e5ac777329af.PNG)


Chrome:

![ToolTipArrow_CHROME](https://user-images.githubusercontent.com/98878781/175562216-389d9b0e-6b11-4e73-8cbc-c3d4bf26261f.PNG)
