### ISSUE TITLE
`TooltipWrapper` when open will change the size of the anchor

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1546]

**Comment by irinelT** [comment]
@iamvukasin Can you provide more details for this ticket?

**Comment by iamvukasin** [comment]
You can try to click any tooltip anchor (for example, the info icon that opens fee tooltip or Settings) and see if the anchor changes its position/size after clicking. They're expected to be unchanged.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/8989109/184380492-e5d12ca8-ce73-4fba-b6fc-3eccf547e35e.png">

<img width="248" alt="image" src="https://user-images.githubusercontent.com/8989109/184380597-63431d60-8607-455b-af61-00825c2ed014.png">

**Comment by irinelT** [comment]
This works.
