### ISSUE TITLE
backdrop for nested `Tooltip` does not occupy entire screen

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1549]
![image](https://user-images.githubusercontent.com/85455/166904233-e32fe3b7-95d0-4a3f-9024-4361a1a4ad04.png)

**Comment by irinelT** [comment]
This is working fine now.

![backdropForNestedTooltipDoesNotOccupyEntireScreen](https://user-images.githubusercontent.com/98878781/176212317-e326dc44-9b89-41ac-865c-3284dfe22998.PNG)
