### ISSUE TITLE
Update pool card flag design

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1572]
Flags on Pool Cards should be updated to match following design:

![Badges](https://user-images.githubusercontent.com/7648077/167481031-94c8cd51-aeda-4a73-b7f7-4e1936bd454a.png)

Figma [link](https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System---Version-%233?node-id=2136%3A24465).

**Comment by irinelT** [comment]
For fixed and matured looks good, however when I filter the inactive ones, the card flag is set as matured.

https://user-images.githubusercontent.com/98878781/175563114-6174da4d-fb78-4942-b94a-768dc16b52c6.mp4
