### ISSUE TITLE
Fixed APR calculation is wrong

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1593]
**Describe the bug**
Fixed APR calculation is not correct.

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Ethereum
URL: app.tempus.finance

**Comment by irinelT** [comment]
Approved by Research team.
https://discordapp.com/channels/823876167584055306/849019424609534022/976899636814020658
