### ISSUE TITLE
Page shakes when dropdown is opened

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1600]
**Describe the bug**
When dropdown is opened, page scrollbar appears, and whole app content moves to the left side (shakes).

**To Reproduce**
1. Open Tempus App.
2. Click on Filter dropdown inside Markets section.

**Expected behavior**
Scroll bar should not appear, and page content should not be pushed to the left.

**Actual behavior**
Page scroll bar appears, and whole page content moves to the left.

**Screenshots**
![Peek 2022-05-16 16-15](https://user-images.githubusercontent.com/7648077/168613705-f7511946-ef1b-4e72-9397-18d6ae623979.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Ethereum
URL: local

**Comment by irinelT** [comment]
When dropdown is opened, scrollbar doesn't appear and the page is not shaking.

https://user-images.githubusercontent.com/98878781/175525811-c3a2c2cf-e06f-44c6-a553-7cbd4accde71.mp4
