### ISSUE TITLE
Background gradient breaks when page is scrolled

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1621]
**Describe the bug**
Background gradient breaks when page is scrolled

**To Reproduce**
1. Open V3 of Tempus App
2. Scroll down.

**Expected behavior**
Background gradient follows page scroll.

**Actual behavior**
Background gradient stays on top of the page and user can see white background when scrolling down.

**Screenshots**
![Peek 2022-05-18 13-49](https://user-images.githubusercontent.com/7648077/169032717-f19ab9af-7de0-41e9-a2b7-187dffdb3241.gif)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: Not connected
Network: Wallet not connected
URL: localhost

**Comment by irinelT** [comment]
Background gradient follows page scroll.

https://user-images.githubusercontent.com/98878781/175510210-79969960-fc76-4dd2-a4ed-6f73123a4e25.mp4
