### ISSUE TITLE
Ethereum coin doesn't match ChainLink price

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1623]
**Describe the bug**
Ethereum coin on Ethereum Fork network does not match with Ethereum price on ChainLink.

**To Reproduce**

1. Go to Staging environment
2. Click on Select Network
3. Select Ethereum Fork
4. Click on Manage button
5. Select ETH in table From
6. Type in 1

**Expected behavior**
Ethereum coin price should match ChainLink price (2055.95$).

**Actual behavior**
Ethereum price is not matching with ChainLink price (3049.83$).

**Screenshots**
![Image](https://user-images.githubusercontent.com/98878781/169522228-5df8b684-9000-4499-9c17-c060e98ad0ce.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: Staging environment.

**Additional context**

**Comment by lazarmitic** [comment]
We are fetching coin prices from ChainLink - in case ChainLink fetch fails, we use CoinGecko as a fallback.

**Comment by lazarmitic** [comment]
Ah, I know what is going on - it seems forked network takes price from chainline at the time of forking - price does not update after fork is done - we probably have to invoke some functions on ChinLink contracts to make them work inside forked environment.
