### ISSUE TITLE
Fixed Yield details are missing

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1624]
**Describe the bug**
When I type in a value on Ethereum Fork network, Fixed Yield details are missing.

**To Reproduce**

1. Go to Staging environment
2. Click on Select Network
3. Select Ethereum Fork
4. Click on Manage button
5. Select ETH in table From
6. Type in a value

**Expected behavior**
Fixed Yield details should be displayed.

**Actual behavior**
Fixed Yield details are missing.

**Screenshots**
![Selection_005](https://user-images.githubusercontent.com/98878781/169036403-01aa693a-5af0-49bd-9dbe-411937070645.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: Staging environment

**Additional context**

**Comment by lazarmitic** [comment]
Does this happen on production pools as well?

**Comment by irinelT** [comment]
No.
