### ISSUE TITLE
Icon for wETH is not showing up inside pool card

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1633]
**Describe the bug**
Icon for wETH is not showing up inside pool card

**To Reproduce**
1. Open Tempus App V3
2. Scroll down to wETH pool card.
3. Inspect card icon in top right corner.

**Expected behavior**
Icon for wETH should show up.

**Actual behavior**
Icon for wETH is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/7648077/169070192-a9f8f9c9-9642-4843-a4a4-d9d29fa906bd.png)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: Wallet not connected
Network: Wallet not connected
URL: localhost

**Comment by irinelT** [comment]
Icon WETH is displayed.

![WETHPoolIconShowing](https://user-images.githubusercontent.com/98878781/175374026-e030e36c-4d00-4062-9b3c-6e48915c05ae.png)
