### ISSUE TITLE
Add PoolsHeading component

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1638]
![unknown](https://user-images.githubusercontent.com/7648077/169243178-377aaefc-7a31-4096-87c0-e654eb3d1c6d.png)

Design [link](https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus%3A-Product---Web-V3?node-id=4735%3A71151).

**Comment by irinelT** [comment]
Pools Heading are displayed on page.

![HeadingEthereumNetworkPool](https://user-images.githubusercontent.com/98878781/175374429-7a2a9401-170b-4e11-a7c3-2001e66cc51c.PNG)
