### ISSUE TITLE
Remove icons for switching between card and table view

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1659]
Since we are not going to add table view as part of the MPV we should remove buttons for switching between table and card views.

**Comment by irinelT** [comment]
Icons for stitching between card and table view are removed.

![IconsForSwtichingTabBetweenPoolCardsAndViewAreRemoved](https://user-images.githubusercontent.com/98878781/175511449-153e8c6e-a218-400c-b601-3d29fe38ad69.PNG)
