### ISSUE TITLE
Dashboard not loaded

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1661]
**Description**
Blank page is loaded upon visiting tempus-app

**To Reproduce**
1. Navigate to V3 testnet.

**Expected behavior**
Pool cards should be displayed.

**Actual behavior**
Blank page is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/98878781/169791910-42984c7a-5bca-4474-9c77-c0a6b9450287.png)
[V3.log](https://github.com/tempus-finance/tempus-app/files/8753471/V3.log)

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: MetaMask
Network: Unknown
URL: V3 testnet

**Additional context**
Not reproducible on unused Firefox.

**Comment by lazarmitic** [comment]
Try again - Alchemy endpoint did not have this testnet URL in it's whitelist.

**Comment by irinelT** [comment]
Now it works. Thanks.
