### ISSUE TITLE
Page content moves left and right on navigation

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1673]
**Describe the bug**
When user navigates from page that has a scrollbar to a page that does not have scroll bar, whole page content moves left and right.

**To Reproduce**
1. Open Tempus App.
2. Open Markets page. Scrollbar is present.
3. Open one of the pools on markets page.

**Expected behavior**
Scrollbar should still be visible after opening pool card (but disabled).

**Actual behavior**
Scrollbar disappears and whole page content moves to the right.

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: Not connected
Network: Wallet not connected
URL: localhost

**Comment by irinelT** [comment]
Page content doesn't left and right on navigation.

https://user-images.githubusercontent.com/98878781/175512639-d00d93f2-366b-40dc-9ef8-8b849697cee5.mp4
