### ISSUE TITLE
Horizontal scrollbar appears when popup is opened

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1675]
**Describe the bug**
When user opens any popup (drop-down, settings menu, tooltip), horizontal scrollbar appears and user can scroll a little bit to the right.

**To Reproduce**
1. Open Tempus App.
2. Open Filters dropdown on Markets page.

**Expected behavior**
Horizontal scrollbar does not appear after dropdown is opened. 

**Actual behavior**
Horizontal scrollbar appears when dropdown is opened.

**Environment**
Operating System: Ubuntu
Browser: Chrome
Wallet: Not connected
Network: /
URL: localhost

**Comment by irinelT** [comment]
Horizontal scrollbar does not appear after dropdown is opened.

![HorizontalScrollbarDoesntAppear](https://user-images.githubusercontent.com/98878781/175372333-dcec54b7-a237-4414-bd24-96bc28466348.PNG)
