### ISSUE TITLE
change the filtering options from checkbox to radio button

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1679]
such that the users will only check one type of pool at a time

https://www.figma.com/proto/0fb8VFsiYRLiAxJX5cFyme/Tempus%3A-Product---Web-V3?page-id=2903%3A39799&node-id=6244%3A299638&viewport=-26298%2C-10238%2C0.77&scaling=min-zoom&starting-point-node-id=6244%3A299638&show-proto-sidebar=1

**Comment by irinelT** [comment]
Done.

![Image](https://user-images.githubusercontent.com/98878781/184342898-77debc7a-09cf-499d-b593-a22b1beab489.png)
