### ISSUE TITLE
Create PoolPositionCard component

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1682]
Create a component that will contain info about user position in the pool.

![image](https://user-images.githubusercontent.com/7648077/170037340-2a907144-c5cc-4b40-a1dc-5cea0d171ec3.png)

**Comment by irinelT** [comment]
This looks good.
![PoolPositionCard](https://user-images.githubusercontent.com/98878781/182883219-62885cc9-ee3d-4a1b-8765-6baa9d11acc9.PNG)
