### ISSUE TITLE
Open PoolPositionModal when user clicks on matured pool in markets page

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1691]
When user clicks on matured pool inside markets page we should open a pool position modal that contains pool info and a button for user to make a withdrawal.

**Comment by irinelT** [comment]
When clicking on a matured pool in Markets Page, it displays a tab that contains pool info and a button for user to make a withdrawal.

![MaturedPoolPosition](https://user-images.githubusercontent.com/98878781/175515173-11d49be1-a65d-482a-ba45-997d59e4ba00.PNG)
