### ISSUE TITLE
Update Fixed APR calculation

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1705]

**Comment by irinelT** [comment]
@irinelT Do we have any documentation about APR calculation?

**Comment by iamvukasin** [comment]
AFAIK we don't at the moment. The idea of this ticket is to align the fixed APR calculation in v3 to one used in v2. You can test by comparing values in both versions.

**Comment by irinelT** [comment]
Doesnt look good.


![Image](https://user-images.githubusercontent.com/98878781/185805158-447fc48b-597c-42c1-8025-96a6c9d4f85b.png)

**Comment by irinelT** [comment]
It matches Prod.


![Image](https://user-images.githubusercontent.com/98878781/185866011-2786f534-09a3-40f8-a42f-02e62033101b.png)
