### ISSUE TITLE
Navigation round corner doesnt load until pools load

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1715]
![Peek 2022-05-31 18-46](https://user-images.githubusercontent.com/85455/171183776-941f1b09-9819-4e11-afa1-9bde89710778.gif)

**Comment by irinelT** [comment]
Navigation round corner loads correctly.

https://user-images.githubusercontent.com/98878781/175516131-2526a15e-e177-4c66-a433-cac3b9880c08.mp4
