### ISSUE TITLE
Pool card loading state

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1728]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/8989109/171595201-0d9726d0-ee8f-4dbd-8020-65df8564e22c.png">

[Figma link](https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus%3A-Product---Web-V3?node-id=6025%3A368346)

**Comment by irinelT** [comment]
Seems to me that this is working now.

https://user-images.githubusercontent.com/98878781/175523952-927e8e17-7dfb-4d9c-b937-f46a09bb22e9.mp4
