### ISSUE TITLE
Closing wallet selection modal breaks the app

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1796]
**To Reproduce**
1. Go to Markets.
2. Click on a pool card.
3. Click on the "Connect Wallet" button.
4. When the wallet selection modal appears, click on the close button without selecting any wallet.

**Expected behavior**
The modal closes and returns to the deposit preview modal.

**Actual behavior**
The app breaks.

**Comment by irinelT** [comment]
This works fine now, the application doesn't break.

https://user-images.githubusercontent.com/98878781/175517640-fcc9c3d6-3be2-4c48-9590-33a34ffcdbfd.mp4
