### ISSUE TITLE
`dateFormatter` in `constants` does not honor user locale

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1818]
it's hardcoded to use `en-GB`.
we should have a date formatter util/class which honor user locale

**Comment by irinelT** [comment]
Not fixed.

User local: USA
Tempus date format: GB

![Image](https://user-images.githubusercontent.com/98878781/185806446-df91ee9e-d0f1-4156-91d0-82f6884f9cb2.png)

**Comment by ShawTim** [comment]
we dont support en-US, so it should fallback to en-GB which is expected

**Comment by irinelT** [comment]
All good in that case.
