### ISSUE TITLE
Filter and Sort dropdown goes below pools

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1852]
![Image](https://user-images.githubusercontent.com/25841025/175270168-645c9357-850e-466d-bcd6-80fc89bf65cf.png)

size Small

**Comment by irinelT** [comment]
This looks fine, FIlter and Sort dropdown are looking good.

https://user-images.githubusercontent.com/98878781/182365087-5b533668-592e-4cad-9e59-73b3e0ac9d0f.mp4
