### ISSUE TITLE
In Sort the arrow is not clickable

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1853]
![Image](https://user-images.githubusercontent.com/25841025/175270469-a6dc45cd-733f-4852-bc73-ac11c51915a0.png)

size Small

**Comment by irinelT** [comment]
This looks fine, the arrow is clickable.

https://user-images.githubusercontent.com/98878781/182364459-ee6862a1-07dd-4493-8aee-304e77adc49e.mp4
