### ISSUE TITLE
Add Notification Service

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1860]
Part of the Notification task

size Medium

**Comment by irinelT** [comment]
I only see MM notifications.
@iamvukasin is this it?


![Image](https://user-images.githubusercontent.com/98878781/185806859-cb9f4059-f478-4df3-8f84-8f4408bdc813.png)

**Comment by iamvukasin** [comment]
More like this:

<img width="284" alt="Screenshot 2022-08-30 at 22 45 47" src="https://user-images.githubusercontent.com/8989109/187624536-5eed7971-1829-418a-bc7d-483d4ecd4fad.png">

**Comment by irinelT** [comment]
Oh, I see. Those notifications work like a charm. Closing the ticket.
