### ISSUE TITLE
Wallet Popup - address

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1863]
Show address and change wallet in the popup

size Medium

**Comment by lazarmitic** [comment]
Moving to blocked until @Olafkuusik gives us a green light that current wallet popup is ready for implementation.

**Comment by irinelT** [comment]
The Wallet popup looks like this:
![WalletAdress](https://user-images.githubusercontent.com/98878781/183069324-ec1d1882-d4f3-49dd-94fc-31bdd9ad1b4d.PNG)
The design matches with the one from: https://www.figma.com/file/fVhZzEU8wILYqSubXiwujD/Tempus%3A-Design-System---V3?node-id=28%3A691
However I can't change wallet in the popup and the transactions are not displayed. Is this finished for V3? @lazarmitic

**Comment by lazarmitic** [comment]
Which network is this on?

**Comment by irinelT** [comment]
Ethereum Fork.

**Comment by lazarmitic** [comment]
Ethereum Fork does not support graph service that's why you can't see any transactions in the wallet popup.

I think change wallet option was removed intentionally, because it's technically not possible for all wallets.

**Comment by irinelT** [comment]
@lazarmitic I still can't change wallet in the popup, however the transactions are displayed on Fantom network.
![WalletPopupFTM](https://user-images.githubusercontent.com/98878781/183909961-477a34d0-6e30-427f-8ca8-f9466b2dfdbf.PNG)
