### ISSUE TITLE
Wallet Popup - transactions

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1864]
Add list of latest transactions to Wallet popup. 
How many transactions? Latest top or earliest top?

size Medium

**Comment by irinelT** [comment]
The transaction is displayed on wallet popup on Fantom network.
![WalletPopupFTM](https://user-images.githubusercontent.com/98878781/183910316-e304a01f-2e90-46e2-a4a1-3c530e17d35f.PNG)
