### ISSUE TITLE
Wallet Popup - transaction history

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1865]
Add list of latest transactions to Wallet popup.
How many transactions? Latest top or earliest top?

size Medium

**Comment by lazarmitic** [comment]
Moving to blocked until @Olafkuusik gives us a green light that current wallet popup is ready for implementation.

**Comment by irinelT** [comment]
The transaction is displayed on wallet popup on Fantom network.
![WalletPopupFTM](https://user-images.githubusercontent.com/98878781/183910144-26ab4a3a-98f2-4724-8626-8cfb54c7340b.PNG)
