### ISSUE TITLE
User balance is not update on user actions

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1869]
size Medium

**Comment by irinelT** [comment]
Looks like user balance is decresed after depositing.
Initial balance: $36.28
Action: Deposit $1
Final balance: $35.28

![Image](https://user-images.githubusercontent.com/98878781/185807300-366e673a-eb25-45e4-81ed-aee98f3ed60c.gif)

**Comment by ShawTim** [comment]
the current balance is talking about wallet balance.
$36.28 -> deposit $1 -> $35.28
