### ISSUE TITLE
On withdraw show underlay page

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1870]
![Image](https://user-images.githubusercontent.com/25841025/175274711-7f632e6a-03bf-43cb-a6f4-b3a46f7fbaa4.png)

size Small

**Comment by irinelT** [comment]
This looks fine.
![WithdrawUnderlayPage](https://user-images.githubusercontent.com/98878781/182840663-2348fcea-86d3-401b-92b8-cef9900569e8.PNG)
