### ISSUE TITLE
In Portfolio Overview, check what values are shown in the top boxes

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1872]
size Small

**Comment by lazarmitic** [comment]
Current balance is fiat balance of all pools combined for user.
Yield Earned is amount of yield that accrued for user. For example if I deposited 100 ETH last month, and my current balance is 103 ETH, that means my Yield Earned is 3 ETH.
Estimated Yield - Based on pool APR and remaining duration we can calculate how much more yield user can earn.

**Comment by danieledamiani** [comment]
`Estimated Yield` should be a sum of potential yield of all pools in Portfolio?

**Comment by lazarmitic** [comment]
Yes

**Comment by irinelT** [comment]
This does not work well when `fork` network is enabled but it works well in production like setup. Closing the ticket.
![image](https://user-images.githubusercontent.com/98878781/195332833-186a528c-dba0-4dcd-ad75-10b775af55ef.png)
