### ISSUE TITLE
Improve error message displaying from MetaMask when failed operation

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1873]
check with Design

size Small

**Comment by irinelT** [comment]
This looks fine, the design matches with the one from Figma.
https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus%3A-Product---Web-V3?node-id=2903%3A39799
![MetaMaskFail](https://user-images.githubusercontent.com/98878781/183063572-963a6dac-3121-4b53-a62a-22ed2daf5258.PNG)
![MetaMaskFail1](https://user-images.githubusercontent.com/98878781/183063592-0990d5b7-37e2-4415-a637-6e4f465fd354.PNG)
