### ISSUE TITLE
Update Blocknative colors to match colors from the app

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1883]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/8989109/175288447-3e8eeaf7-e9d9-4322-9880-b9f50c8017b9.png">

* Primary color
* Success color
* Warning color
* Danger color

[Docs reference](https://docs.blocknative.com/onboard/core#custom-styling)

**Comment by lazarmitic** [comment]
Moving to blocked until we get a confirmation from design team.

**Comment by iamvukasin** [comment]
The colors are updated in Figma now.

**Comment by irinelT** [comment]
![Image](https://user-images.githubusercontent.com/98878781/184321658-4684d273-8453-4321-969c-524cff524c54.png)
