### ISSUE TITLE
Disable withdrawal from a matured pool if user hasn't deposited

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1886]

**Comment by irinelT** [comment]
This looks fine, the Withdraw button is removed if the user hasn't deposited in a matured pool.

![WithdrawalButtonRemovedIfUserHasntDepositedInAMaturedPool](https://user-images.githubusercontent.com/98878781/182384269-3ed07335-425f-4f56-beb7-6afc4ff1227c.png)
