### ISSUE TITLE
input amount `0.01` in USDC pool will kill the page

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1895]
![image](https://user-images.githubusercontent.com/85455/175397225-5733f9b0-2881-4dfa-9962-3c607c128662.png)

the root cause is becoz error throw for `estimatedDepositAndFix()` for small amount with token with lower precision (USDC is 6)
adding `catchError()` for the `Observable` in `useYieldAtMaturity` should solve the problem
but the question is why the unit test cases have not covered (which it should, if not, then how to simulate this?)

**Comment by irinelT** [comment]
This is now fixed. I successfully deposited 0.01 USDC.



https://user-images.githubusercontent.com/98878781/183920223-2393d822-005f-44b9-a193-a9a262a18b6a.mp4
