### ISSUE TITLE
[Web] Section Hero

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1908]
- Hero (text and design confirmed)
  - hard code avatars?
  - twitter handles animation?
  - each links to twitter owner

![Image](https://user-images.githubusercontent.com/25841025/175959659-cfaab9b0-6566-4f31-99dd-eea881022163.png)

**Comment by lazarmitic** [comment]
We decided to remove avatars from hero section, only header text was left.
