### ISSUE TITLE
[Web] Header

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1910]
![Image](https://user-images.githubusercontent.com/25841025/175959357-f361eb2a-fa16-44cd-8caf-4b7f23affc04.png)

- Header (text and design confirmed)
  -  links need active status
  - new Logo links to the top 
  - Product links at Products section
  - Contributors TBD ?
  - Token links to Token section
  - Docs links to tempus documentation 
  - Blog links to Medium

**Comment by irinelT** [comment]
The Header is different on the website and has different label names. However the links are working well.

https://user-images.githubusercontent.com/98878781/183437822-1472b323-8bf5-4aef-9287-65a7c7ab8e7a.mp4

**Comment by lazarmitic** [comment]
Header content was changed intentionally after initial implementation.
