### ISSUE TITLE
[Web] Section `Invest in the Future`

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1914]
- Invest in the Future (design and text confirmed)
 - links to token to CG and CMC

![Image](https://user-images.githubusercontent.com/25841025/175960998-7389cf39-0678-4635-a9f5-b6381609198f.png)

**Comment by irinelT** [comment]
The section's name is different on the website. It's name is "Powered by TEMP".
![InvestInTheFuture](https://user-images.githubusercontent.com/98878781/183438763-d4a60b02-ef48-43a5-9023-8c8c7c8ce874.png)

The links are working fine.


https://user-images.githubusercontent.com/98878781/183438887-8dc70f40-e7c1-44bd-840d-322abb88147b.mp4

**Comment by lazarmitic** [comment]
This was intentionally changed.
