### ISSUE TITLE
[Web] Section `Our investors`

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1916]
- Our investors (design and text confirmed)
 - only logos, no links

![Image](https://user-images.githubusercontent.com/25841025/175961564-bf43eca7-6354-4c57-b186-5edcb9b239b7.png)

**Comment by irinelT** [comment]
It looks fine. Only logos, no links.

https://user-images.githubusercontent.com/98878781/182411007-089e397f-1253-4e42-a90f-d49a35f87c6d.mp4
