### ISSUE TITLE
[Web] Section `Blog`

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1917]
- Blog (design and text confirmed)
 - link to Medium
 - show the last 3 articles

![Image](https://user-images.githubusercontent.com/25841025/175961808-04daf3c1-8dc6-4517-88c2-ff218ad5bd5d.png)

**Comment by irinelT** [comment]
It works fine. "Read more on our Blog" links to Medium. All the articles links to the desired page. Also the last three articles are displayed.

https://user-images.githubusercontent.com/98878781/182420682-9501ef77-425b-4ad6-b293-70b6c139b307.mp4
