### ISSUE TITLE
[Web] Section `Footer`

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1919]
- Footer (design and text confirmed)

![Image](https://user-images.githubusercontent.com/25841025/175962185-61ad5785-f7d7-48af-a41e-9a36b01b19ee.png)

**Comment by irinelT** [comment]
Footer is different on the website.
![Footer](https://user-images.githubusercontent.com/98878781/183436616-5012e4d2-09ac-4110-8722-6e17db1a0cca.PNG)

**Comment by lazarmitic** [comment]
Footer design was changed after initial implementation.
