### ISSUE TITLE
[Web] Mouse over effect

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#1920]
mouse over link
![Image](https://user-images.githubusercontent.com/25841025/176904399-0a5e9095-e517-4744-a682-3ff3c5283d60.png)

**Comment by irinelT** [comment]
Looks good.


https://user-images.githubusercontent.com/98878781/210828491-52d59e67-5767-4c3a-8f49-1fbf8c409796.mp4
