### ISSUE TITLE
`ErrorModal` should have better handling for metamask (or wallet) error

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#1924]
https://www.figma.com/file/0fb8VFsiYRLiAxJX5cFyme/Tempus%3A-Product---Web-V3?node-id=2903%3A39799

need to detect wallet error and show some error text

**Comment by irinelT** [comment]
Works as expected.


![Image](https://user-images.githubusercontent.com/98878781/185906986-93d9595b-d02f-4088-8cc9-310ffc3f4c15.png)
