### ISSUE TITLE
[Web] Add hover over effect for avatar images in hero section

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1937]
![Image](https://user-images.githubusercontent.com/7648077/176184927-36bbe7ef-b15f-407c-a55e-f2ddf58d7691.png)

**Comment by irinelT** [comment]
Avatars are missing from the webpage.

https://user-images.githubusercontent.com/98878781/183439230-8575a79d-ba2c-4c13-b9c7-0382ac41a7b1.mp4

**Comment by lazarmitic** [comment]
We decided to remove avatars and release without them.
