### ISSUE TITLE
[Web] Update footer with new content from design

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#1957]
![Image](https://user-images.githubusercontent.com/7648077/176619698-744cf755-0434-455b-9546-886520dd6e85.jpg)

**Comment by irinelT** [comment]
On the website the footer is a bit different from this one.
Instead of Tokenomics -> TEMP.
We're Hiring -> Jobs.
Legal -> Admin.
There is also a new label "Branding".

![UpdateFooterWithNewDesign](https://user-images.githubusercontent.com/98878781/182424842-702e3f73-4256-4e26-b5c2-f090fbbbc625.png)

**Comment by lazarmitic** [comment]
All of these were intentionally changed.

**Comment by irinelT** [comment]
Working as expected.
