### ISSUE TITLE
UI doesn't update when unsupported network is selected in wallet

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#1959]
**To Reproduce**
1. Go to Metamask
2. Change the network to an unsupported one (e.g. Polygon)

**Expected behavior**
The UI should change:
* Wallet should show that the selected network is unsupported
* Pool list should show all Tempus pools.

**Actual behavior**
The wallet keeps the same network and the pool list stays unchanged.

**Comment by irinelT** [comment]
This works fine now.

https://user-images.githubusercontent.com/98878781/182430079-bd6dc46c-e59e-4139-a23d-38253e546609.mp4
