### ISSUE TITLE
[Web] Token link doesn't work

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1981]
**Describe the bug**
When you click on the Token on top of the page nothing happens.

**To Reproduce**
1. Go to Staging environment
2. Click on Token

**Expected behavior**
The Token label should link to the desired page.

**Actual behavior**
Nothing happens when Token is clicked.

**Screenshots**

![TokenLink](https://user-images.githubusercontent.com/98878781/176903565-acb1fd20-d26c-4d2a-853c-8c39848a6089.png)

**Environment**
Operating System: Window
Browser: Chrome
Wallet: None
Network: None
URL: Staging environment

**Additional context**

**Comment by ShawTim** [comment]
becoz token page was not yet available. it should be there now.

**Comment by irinelT** [comment]
Token link now links to its desired page.

https://user-images.githubusercontent.com/98878781/182389979-342fb62d-72db-4f46-b648-32bc99a2422d.mp4
