### ISSUE TITLE
[Web] Tokenomics button links to Homepage

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1990]
**Describe the bug**
When clicking on Tokenomics on the bottom of the page, it links to Homepage.

**To Reproduce**
1. Go to Staging environment
2. Scroll down to the bottom of the page
3. Click on "Tokenomics"

**Expected behavior**
The label "Tokenomics" should link to its desired page.

**Actual behavior**
The label links to the Homepage

**Screenshots**
![TokenomicsLinkLinksToHomepage](https://user-images.githubusercontent.com/98878781/176914541-1c25947a-db4c-496e-bc58-6304e60d07bf.png)

**Environment**
Operating System: Window
Browser: Chrome
Wallet: None
Network: None
URL: Staging environment

**Additional context**

**Comment by ShawTim** [comment]
the link should have been fixed.

**Comment by irinelT** [comment]
The link works good now, however the label name is changed to TEMP, just asking if this was changed intentionally?

https://user-images.githubusercontent.com/98878781/182389021-244b96d4-2797-409b-a811-8261e76e46a9.mp4

**Comment by lazarmitic** [comment]
Yes, link was intentionally changed to TEMP

**Comment by irinelT** [comment]
That this works well. I'm going to close it.
