### ISSUE TITLE
[Web] Tempus Labs button links to Homepage

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#1991]
**Describe the bug**
When clicking on Tempus Labs on the bottom of the page, it links to Homepage.

**To Reproduce**
1. Go to Staging environment
2. Scroll down to the bottom of the page
3. Click on "Tempus Labs"

**Expected behavior**
The label "Tempus Labs" should link to its desired page.

**Actual behavior**
The label links to the Homepage

**Screenshots**
![TempusLabsLinkLinksToHomepage](https://user-images.githubusercontent.com/98878781/176915092-de7531e9-b376-4630-b410-9c06e85b00ef.png)

**Environment**
Operating System: Window
Browser: Chrome
Wallet: None
Network: None
URL: Staging environment

**Additional context**

**Comment by ShawTim** [comment]
the link should have been fixed

**Comment by irinelT** [comment]
Tempus Labs link now works fine.

https://user-images.githubusercontent.com/98878781/182390733-8ce60cf0-3bfe-4986-be6c-032c1e3bc17f.mp4
