### ISSUE TITLE
[Web] Responsive investors section

### ISSUE THREAD

**Issue by iamvukasin** [tempus-finance/tempus-app#2006]

**Comment by irinelT** [comment]
Investors section is responsive. I've tested on different screens sizes and I've tested it on mobile as well.

![InvestorsLogosHaveTooMuchWhiteSpaceOnSmallScreensAndTheyBreakTheLayoutOfThePage](https://user-images.githubusercontent.com/98878781/210811894-2ee2f949-889e-4e62-ac92-ff31014b9b85.png)
