### ISSUE TITLE
[Web] Header improvements

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2040]
1.   remove `Products` link 
2.   should `Contributors` be renamed `Team`?
3.   should `Contributors` go to `/team` or `/contributors`?
4.   should `Token` be renamed `Tokenomics` and go to `/tokenomics`?
5.   should `Blog` be renamed `Medium`?

**Comment by RTP2016** [comment]
1. should Contributors be renamed Team? Yes let's keep the team as it is today. 
2. should Contributors go to /team or /contributors? /team
3. should Token be renamed Tokenomics and go to /tokenomics? yes
4. should Blog be renamed Medium? no keep to blog

**Comment by irinelT** [comment]
This looks good.
