### ISSUE TITLE
[Web] `Products` improvements

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2041]
1.  In card button the button is left aligned
2.  Should we rename `Nostra Money`? 
3. `Coming soon` button not like the design 
4.  Card mouse over effect looks broken

iPad portrait
1. display 1 card per line

**Comment by RTP2016** [comment]
Should we` rename Nostra Money? Not yet. Undecided. Keep generic for now

**Comment by irinelT** [comment]
This is no longer relevant as the "Products" was removed.
