### ISSUE TITLE
[Web] `Invest in the Future` improvements

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2042]
1. no mouse over effect on boxes?

iPhone portrait
    - arrow is left aligned, should be right aligned?

**Comment by RTP2016** [comment]
@Olafkuusik perhaps can comment. Don't think it's necessary but nice to have potentially

**Comment by Olafkuusik** [comment]
Interactions with the cards can be as follows:
1. Whole card is clickable and opens new tab/window depending on user browser preference
2. card hover state changes cursor to pointer
3. card inverts colors, adds 3px stroke and moves 8px up.

figma prototype should be visible (Flow 3) here:
https://www.figma.com/proto/rby2HM3kR4W59V5VG1Y1Tc/Tempus-rebrand-website-explorations?page-id=1215%3A16386&node-id=1663%3A11275&viewport=4091%2C-1624%2C0.66&scaling=min-zoom&starting-point-node-id=1663%3A11275&show-proto-sidebar=1

**Comment by irinelT** [comment]
"Invest in the Future" section changes its name to "Powered by TEMP" and looks good.


https://user-images.githubusercontent.com/98878781/211042725-7542a6f2-bb23-44b7-92d5-aacc2a009f9c.mp4
