### ISSUE TITLE
[Web] `Blog` improvements

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2045]
- no mouse over effect on blog card

iPad/iPhone portrait
- display 1 card per line

**Comment by Olafkuusik** [comment]
Interactions with the blog card could be as follows: 

1. Whole card area is clickable and leads to article is hover-able
2. Hover moves the card by 16px up in ease out motion (tween time 300ms)
Prototype visible here (Flow 2)
3. Mouse changes to pointer cursor when over blog card indicating a link
https://www.figma.com/proto/rby2HM3kR4W59V5VG1Y1Tc/Tempus-rebrand-website-explorations?page-id=1215%3A16386&node-id=1663%3A10834&viewport=4091%2C-1624%2C0.66&scaling=min-zoom&starting-point-node-id=1663%3A10834&show-proto-sidebar=1

**Comment by irinelT** [comment]
Looks good.


https://user-images.githubusercontent.com/98878781/210830912-145b1f69-8ec1-4aa6-93ba-e5bbab5a7399.mp4
