### ISSUE TITLE
[Web] Build on StarkNet badge text does not render properly on smaller screens

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#2069]
![image](https://user-images.githubusercontent.com/7648077/177712381-a222a213-47fb-4613-8206-ec0d5c669815.png)

Text should be on a single line.

**Comment by irinelT** [comment]
Seems to work fine now, I've also checked it on mobile.


https://user-images.githubusercontent.com/98878781/210809405-0af0ccae-7250-4ca2-9257-91c847aa6352.mp4
