### ISSUE TITLE
[Web] Investors logos have too much white space on small screens, and they break the layout of the page

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#2071]

**Comment by irinelT** [comment]
Seems to be fixed. I've also tested this on mobile.

![InvestorsLogosHaveTooMuchWhiteSpaceOnSmallScreensAndTheyBreakTheLayoutOfThePage](https://user-images.githubusercontent.com/98878781/210810964-56247a0a-02ff-4271-8fe8-71a23334c677.png)
