### ISSUE TITLE
[Web] Menu icon color is not correct on Team and Token pages

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#2074]
![Image](https://user-images.githubusercontent.com/7648077/177722746-eb811beb-a255-4fc9-93e1-c27658171541.png)

**Comment by irinelT** [comment]
Team page:

![MenuIconColorIsNotCorrectOnTeamAndTokenPages](https://user-images.githubusercontent.com/98878781/211040986-3618ecff-9459-4cae-828a-1aff490a2e1f.png)


Token page:

![MenuIconColorIsNotCorrectOnTeamAndTokenPages1](https://user-images.githubusercontent.com/98878781/211041023-a93597f4-f15d-40ea-b11b-af34cd69e790.png)
