### ISSUE TITLE
[Web] Rename every instance of `Tokenomics` to `Token`

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2102]
TBC

![Image](https://user-images.githubusercontent.com/25841025/177835856-5a268b29-42cf-4dfe-87a5-1a675472645f.jpeg)

**Comment by irinelT** [comment]
Looks good.

![RenameEveryInstanceOfTokenomicsToToken](https://user-images.githubusercontent.com/98878781/210837337-373788a0-b2d2-4668-ad0e-5f185fae6797.png)
