### ISSUE TITLE
[Web] background ribbon for the product section

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#2122]
![image](https://user-images.githubusercontent.com/85455/177986216-54bb8b0b-f012-47f4-aa7b-9078410fe706.png)

**Comment by irinelT** [comment]
Background for the product section looks good.

![BackgroundRibbonForTheProductSection](https://user-images.githubusercontent.com/98878781/211039764-5924d041-e169-4717-9574-4c5fff5011d1.png)
