### ISSUE TITLE
[Web] Update `David` pic

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2144]
![Image](https://user-images.githubusercontent.com/25841025/178234524-bc018dc3-d446-4320-854b-0fcf68ce6595.png)

**Comment by irinelT** [comment]
David's picture is updated.

![UpdateDavidPic](https://user-images.githubusercontent.com/98878781/211039974-988f2f3b-1794-4741-bcf1-f784dfa02339.png)
