### ISSUE TITLE
[Web] Add `Discord` icon to Hero CTA

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2165]
![Image](https://user-images.githubusercontent.com/25841025/178275000-8fccd3ae-4614-4a97-b571-862bef07342f.png)

**Comment by irinelT** [comment]
Looks good.

![AddDiscordIconToHeroCTA](https://user-images.githubusercontent.com/98878781/211034152-2abfcf26-651e-48f5-babe-8ffd355ee9ca.png)
