### ISSUE TITLE
[Web] on the homepage ser after ""governance" we should insert the word "process"

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#2169]

**Comment by irinelT** [comment]
Homepage:

![OnTheHomepageSerAfterGovernanceWeShouldInsertTheWordProcess](https://user-images.githubusercontent.com/98878781/211034666-3914c058-c6d8-4051-b365-5748d59c2a53.png)


Team page:

![OnTheHomepageSerAfterGovernanceWeShouldInsertTheWordProcess1](https://user-images.githubusercontent.com/98878781/211034746-e77c34fb-da0c-40d0-b8d0-24c0e826f514.png)
