### ISSUE TITLE
[Web] Add spinner to token stats when loading 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#2175]
At the moment it takes a while to fetch the token stats. It may not be obvious to a user that something is loading. 

Suggestion: 
1. Add a spinner for when the information is being fetched
2. store the fetched information in a cache so that the page doesn't need to fetch each time it is refreshed (at least in the same session).

**Comment by irinelT** [comment]
Looks fine.


https://user-images.githubusercontent.com/98878781/211033387-80a136f3-978c-440f-85d1-c6dcce487fa8.mp4
