### ISSUE TITLE
[Web] Update position of the background pattern on mobile

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#2178]
Reposition background pattern on mobile to be behind number and consistent with home page (see attached)

<img width="183" alt="tempus home" src="https://user-images.githubusercontent.com/17698024/178294195-b0671594-6c17-47e1-a0e8-61300de8fd7d.PNG">
<img width="306" alt="tempus home 2" src="https://user-images.githubusercontent.com/17698024/178294442-a6ab6ffc-82a5-4418-a890-a97b9eafec6c.PNG">

**Comment by irinelT** [comment]
Looks good.
