### ISSUE TITLE
[Web] Update company logos on Team page

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#2182]
Update company logos on team page as per Discord

**Comment by RTP2016** [comment]
![image](https://user-images.githubusercontent.com/17698024/178319209-c24180cd-2a09-47e3-b516-37bb61f109ba.png)

**Comment by irinelT** [comment]
Looks good.

![UpdateCompanyLogosOnTeamPage](https://user-images.githubusercontent.com/98878781/211032920-73079047-9b6e-45eb-9c6b-f25891ddf9ab.png)
