### ISSUE TITLE
[Web] update Treasury section text

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#2188]
![image](https://user-images.githubusercontent.com/85455/178324416-3565be12-5fce-46f9-81f3-4611c9536097.png)

**Comment by irinelT** [comment]
"Treasury" section text updated.

![UpdateTreasurySectionText](https://user-images.githubusercontent.com/98878781/210823774-5a47dccd-69fb-4afd-8f12-3ff006a43256.png)
