### ISSUE TITLE
[web] update "check active grants"'s link

### ISSUE THREAD

**Issue by yarmun** [tempus-finance/tempus-app#2195]
On https://stage-tempus.web.app/governance
![image](https://user-images.githubusercontent.com/39115449/178408753-88e14cd0-98b6-4ec6-8c2b-2ee94a2af8bb.png)

When clicking on "Check active grants", it takes you to https://www.notion.so/tempusfinance/Tempus-Grants-Program-c54b4410e9db49139347210d5a340c5e
But this is an internal link.
If a non Tempus staff opens it (e.g. in Private Browser mode), it prompts this:
![image](https://user-images.githubusercontent.com/39115449/178408649-b4df920e-db53-48d7-a99e-50cfbb5416f3.png)

Thus, we should just set the link directly to https://tempusfinance.notion.site/tempusfinance/Tempus-Grants-Program-c54b4410e9db49139347210d5a340c5e
so it opens directly.

**Comment by irinelT** [comment]
"Check active grants" link redirects to: https://tempusfinance.notion.site/Tempus-Grants-Program-c54b4410e9db49139347210d5a340c5e
I've also tested this to see if it works in incognito.

https://user-images.githubusercontent.com/98878781/210824220-db3c318d-688f-4ed8-86b0-1dfb896d5046.mp4
