### ISSUE TITLE
[Web] Spinner should support dark color

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#2203]
![Image](https://user-images.githubusercontent.com/85455/178449936-c62d0cb4-4663-41fd-bd64-8a47dd123a5e.png)

**Comment by irinelT** [comment]
Looks good.


https://user-images.githubusercontent.com/98878781/210826989-b5356a8a-8cff-4f04-85ac-1bb1bf0ea5f9.mp4
