### ISSUE TITLE
different wallets are sharing the same transaction history on same browser

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#2250]
user should see the transaction history for corresponding address only
since right now we use `localStorage` to manage transaction history we are sharing them within the same browser
this can be fixed by #2249 or any other work around

**Comment by irinelT** [comment]
Works as expected.

![Image](https://user-images.githubusercontent.com/98878781/185805443-72ddd6f5-b6f0-421f-925b-e05b7ebe47b7.gif)
