### ISSUE TITLE
Deposit Ethereum Fork Failed

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#2262]
**Describe the bug**
I tried to deposit some Ethereum Fork and it displayed an error message.

**To Reproduce**
1. Go to Staging environment
2. Click on Swith Network
3. Select Ethereum Fork
4. Click on Ethereum Fork Pool Card
5. Click on Make Deposit
6. Introduce a number you want to deposit

**Expected behavior**
Money should be deposited on the account.

**Actual behavior**
An error message is displayed.

**Screenshots**
![DepositFailed](https://user-images.githubusercontent.com/98878781/182183291-2005af08-d724-4e6d-aa14-755a48cbd284.png)

**Environment**
Operating System: Window
Browser: Chrome
Wallet: MetaMask
Network: Ethereumn Fork
URL: Staging environment

**Additional context**

**Comment by lazarmitic** [comment]
You need to reset your account in metamask

**Comment by irinelT** [comment]
Reset fixed Deposit.

![image](https://user-images.githubusercontent.com/98878781/182243889-563c7fba-e0eb-4e43-8b37-7138f65aa4ab.png)
