### ISSUE TITLE
Portfolio overview Total Yield chart is not visible

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#2279]
**Describe the bug**
The Portfolio overview chart on Total Yield is not visible.

**To Reproduce**
1. Go to Staging environment
2. Click on Portfolio
3. Click on Overview
4. Click on Total Yield

**Expected behavior**
The chart should be visible.

**Actual behavior**
The chart is not visible

**Screenshots**

https://user-images.githubusercontent.com/98878781/183122335-4a56202a-6ead-4bfd-9bfc-35ff908bfd8c.mp4

**Environment**
Operating System: Window
Browser:[Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: Staging environment

**Additional context**

**Comment by lazarmitic** [comment]
Ethereum Fork does not support graph service, that's why you can see chart data on it. Please use Fantom or Ethereum networks to test charts.

**Comment by irinelT** [comment]
Works well on Fantom network, I will close this.

![TotalYieldChart](https://user-images.githubusercontent.com/98878781/184128771-45d16dbd-339a-4c52-b788-de271d59cb50.PNG)
