### ISSUE TITLE
Portfolio overview Total Value chart is not visible

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#2280]
**Describe the bug**
The Portfolio overview chart on Total Value is not visible.

**To Reproduce**
1. Go to Staging environment
2. Click on Portfolio
3. Click on Overview
4. Click on Total Value

**Expected behavior**
The chart should be displayed.

**Actual behavior**
The chart is not visible.

**Screenshots**

https://user-images.githubusercontent.com/98878781/183123375-ad7d882b-1169-4bde-b462-f6df6b5d59b0.mp4

**Environment**
Operating System: Window
Browser: Chrome
Wallet: MetaMask
Network: Ethereum Fork
URL: Staging environment

**Additional context**

**Comment by lazarmitic** [comment]
Ethereum fork does not support graph service, so all of the charts and some of the statistical values in the ui will be missing. Please use Fantom network to test these.

**Comment by irinelT** [comment]
Working on Fantom network, I will close this.

![TotalValueChart](https://user-images.githubusercontent.com/98878781/184128625-94666c94-7192-4b06-932b-583c4f3e3c36.PNG)
