### ISSUE TITLE
[Web] Update Money Market Card

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#2283]
Update card on home page to reflect image attached

<img width="650" alt="nostra tempus website" src="https://user-images.githubusercontent.com/17698024/184617577-a9589b3c-7a96-44e5-a788-eff4b27be96b.PNG">
d

**Comment by irinelT** [comment]
"Money Market Card" updated.

![UpdateMoneyMarketCard](https://user-images.githubusercontent.com/98878781/210835640-c12868c1-3eba-4033-94b0-6380b3c9b3ed.png)
