### ISSUE TITLE
Balance is different on Deposit vs Withdrawal

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#2287]
**Describe the bug**
Displayed USDC balance is different on Deposit and Withdrawal modal.

**To Reproduce**
1. Go to Stage environment
2. Select USDC pool.
3. Make Deposit.
4. Inspect Balance (35 USDC).
5. Go to Portfolio/Positions/Make Withdrawal.
6. Inspect Balance (1 USDC)

**Expected behavior**
Balance should be the same on Balance and Withdrawal.

**Actual behavior**
Balance is $1 on Withdrawal.
Balance is $35 on Deposit.

**Screenshots**

![image](https://user-images.githubusercontent.com/98878781/185807705-7d9f0017-eff2-4c22-9183-4d4c5f936e41.png)

**Environment**
Operating System: Window
Browser: Chrome
Wallet: MetaMask
Network: Fantom
URL: Staging environment

**Comment by ShawTim** [comment]
current balance in deposit modal = wallet balance
available to withdraw in withdraw modal = user pool balance

**Comment by irinelT** [comment]
Got it, thanks.

Working as expected.
