### ISSUE TITLE
Error prompts for failing estimating gas when deposit

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#2303]
![Image](https://user-images.githubusercontent.com/85455/189822667-396adf35-3bd2-446d-abe5-b5f7a130a616.png)

- should already have approval the required amount but it still prompts for insufficient allowance
- why failing for estimating gas
- error message overflow

**Comment by irinelT** [comment]
I got similar on withdrawal.


![Image](https://user-images.githubusercontent.com/98878781/193796578-ea6c692f-8a31-4193-b2c1-88c8fa5cc277.png)

**Comment by irinelko** [comment]
Seems like everything works fine now:


https://user-images.githubusercontent.com/46001191/194584158-1e777e94-bed6-4f54-816a-7c7e0328e358.mp4

**Comment by irinelT** [comment]
Seems like everything works fine now:


https://user-images.githubusercontent.com/98878781/194585834-d7b503f1-4052-459a-9b12-f02c615773f4.mp4
