### ISSUE TITLE
Show `time to maturity left` in the dashboard - needs review

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#234]

**Comment by Olafkuusik** [comment]
Parent pool showing earliest and latest maturity.
If the parent row has just single child pool then show Time to maturity with date.
Child pool shows: day(s) and when less than 24 hours remaining then shows hour(s).
The maturity loading indicator has been removed.

![image](https://user-images.githubusercontent.com/22838368/155524207-eb12a21e-5ba5-4c86-ac7e-0015003ad896.png)

**Comment by lazarmitic** [comment]
@Olafkuusik Let me know if it's fine like this.

![image](https://user-images.githubusercontent.com/7648077/157306187-ea4a3358-d7b2-4936-852e-f2992f070ef3.png)

**Comment by irinelT** [comment]
This is done.

![image](https://user-images.githubusercontent.com/98878781/157449837-37f48b23-26d1-4caa-973b-d947f404d332.png)
