### ISSUE TITLE
it's not obvious what date in the notification represents - maybe we should add 'matures on (date)'

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#342]

**Comment by danieledamiani** [comment]
What's the expected outcome? @RTP2016 @Olafkuusik ?

**Comment by RTP2016** [comment]
Thanks. Just looking at this...

**Comment by Olafkuusik** [comment]
2 mockups representing possible solution to clarify the dates: time of the message and maturity date of the pool they have interacted with
![image](https://user-images.githubusercontent.com/22838368/155521251-77e09404-a4dd-4af6-930d-50319b35d178.png)

**Comment by RTP2016** [comment]
Is that clear now @danieledamiani ?

**Comment by danieledamiani** [comment]
much better, thanks

**Comment by irinelT** [comment]
Notification for Withdrawal is good.
Notification for Approval is bad.

![image](https://user-images.githubusercontent.com/98878781/156362945-5df19586-b359-4cde-bff1-617584363c99.png)

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/157057864-dfb2214e-3ac2-4bee-a191-e6c6602099a3.png)
