### ISSUE TITLE
Variable APR figure (in Dashboard and in Pool View) doesn't update after the user performs an action (I tried with Simple/Deposit/Fixed which really changes the Variable APR if the user wants to do that subsequently), need to refresh page.

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#362]
This could also be solved by having periodic updates (x seconds) to all Fixed and Variable APR figures in Simple/Deposit, and in Dashboard too

**Comment by lazarmitic** [comment]
Fixed in last update. APR values are now updated every time new block is mined.
