### ISSUE TITLE
Pending txs: Replace static three dots with three dots loader in top right

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#372]
![image](https://user-images.githubusercontent.com/78982233/137269181-af03c380-44f6-4bc8-bf22-a8de707a74e4.png)

**Comment by ShawTim** [comment]
![image](https://user-images.githubusercontent.com/85455/158803830-f408a1fa-5103-4e97-ae79-d68f262f59dd.png)
use spinner instead

**Comment by irinelT** [comment]
Spinner implemented successfully.
