### ISSUE TITLE
Populate notifications with actual on-chain data

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#373]
Simple/Deposit/Fixed

![image](https://user-images.githubusercontent.com/78982233/137270305-20e11379-a042-4f03-8857-a8e35b4149ad.png)
![image](https://user-images.githubusercontent.com/78982233/137270321-54be33b9-87bb-4a2d-bdef-26a8af1066c8.png)

Simple/Deposit/Variable

![image](https://user-images.githubusercontent.com/78982233/137271137-a99a621e-0ed2-4670-8fde-ed0deb977e6f.png)
![image](https://user-images.githubusercontent.com/78982233/137271156-2cedb57e-3510-4e25-980d-9ba49349756d.png)

Advanced/Mint

![image](https://user-images.githubusercontent.com/78982233/137271391-ae5bac47-b38b-4f15-9aef-f804cb5e4772.png)

Advanced/Swap - This is wrong, it also shows the estimate, not the actual swapped amount.

![image](https://user-images.githubusercontent.com/78982233/137272284-a1e334d0-4f18-48f1-b48e-a0c6ebab1401.png)

Simple/Withdraw

[x] Principals, [x] Yields, [x] LP tokens to [x] stETH/ETH (dynamic based on what we're swapping to what, fill with actual numbers from tx)

Advanced/ Redeem

[x] Principals and Yields to [x] stETH/ETH (dynamic based on what we're swapping to what, fill with actual numbers from tx)

**Comment by davgarai** [comment]
![image](https://user-images.githubusercontent.com/78982233/137850630-4b781fa0-6496-411d-87d3-c137e13d5783.png)
This has not been fixed yet

**Comment by lazarmitic** [comment]
Closing this one, if this error pops up again. Please re-open the issue.
