### ISSUE TITLE
Bug in dashboard showing wrong value for available to deposit

### ISSUE THREAD

**Issue by mijovic** [tempus-finance/tempus-app#387]
<img width="160" alt="Screenshot 2021-10-15 at 09 50 45" src="https://user-images.githubusercontent.com/23421619/137451994-9c854db9-1813-476a-a8d4-34a11ecedf25.png">

And the actual balance is:
<img width="467" alt="Screenshot 2021-10-15 at 09 51 30" src="https://user-images.githubusercontent.com/23421619/137452035-dce79547-5d86-403f-9808-80ca9180a324.png">

I know it can't fit, but I think it is better to show `0` instead of `1e-1` which is actually `0.1` which is wrong.

**Comment by lazarmitic** [comment]
fixed
