### ISSUE TITLE
Add explanation card for each advanced view

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#518]
Check with @davgarai and @Olafkuusik for context and layout of the cards.

**Comment by danieledamiani** [comment]
component done, waiting for copy

**Comment by danieledamiani** [comment]
Copy can be found in https://docs.google.com/spreadsheets/d/1gWY7o3VHhIcvjZRMjEVnIvyKeX2ZOCf5FxlsUX55YMk/edit#gid=0
