### ISSUE TITLE
After declining a deposit transaction in MetaMask user receives error that deposit failed

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#642]
We should probably handle declines by user, and show a notification that user declined the tx, or don't show any notification at all.

**Comment by Olafkuusik** [comment]
@RTP2016 Please provide a copy for this message

**Comment by RTP2016** [comment]
We can just use: "Deposit declined. Please try again."

**Comment by irinelT** [comment]
Should we change title from "Deposit Failed" to "Deposit declined"?

**Comment by ShawTim** [comment]
> Should we change title from "Deposit Failed" to "Deposit declined"?

personally i think "deposit failed becoz deposit has been declined" so imo that makes senses. welcome for opinions from others.

**Comment by irinelT** [comment]
Please adjust the title to "Deposit declined" as per [Discord discussion](https://discord.com/channels/823876167584055306/940616834456096808/961281520398635010).

**Comment by irinelT** [comment]
Done.

![image](https://user-images.githubusercontent.com/98878781/162797800-ea3859e3-f940-47ea-a79c-ab669270f331.png)
