### ISSUE TITLE
Profit and loss backing token amount briefly goes down when providing liquidity and then goes back to correct value (initial value) 

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#662]

**Comment by lazarmitic** [comment]
This is pretty old issue - and since we are getting close to code freeze I will move it to 2.2 release.

**Comment by lazarmitic** [comment]
I'm not able to reproduce this any more, I tried to provide liquidity in USDT pool on Fantom network.

**Comment by irinelT** [comment]
This is not reproducible.
