### ISSUE TITLE
Profit and loss backing token value briefly goes up when removing liquidity and then goes down to correct value (initial value)

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#663]

**Comment by lazarmitic** [comment]
This is pretty old issue - and since we are getting close to code freeze I will move it to 2.2 release.

**Comment by lazarmitic** [comment]
I'm not able to reproduce this any more, I tried to remove liquidity in USDT pool on Fantom network.

**Comment by irinelT** [comment]
This is not reproducible.
