### ISSUE TITLE
Show variable APR calculation tooltip

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#675]
On the Dashboard, when click on variable APR value, show a popup with the calculation breakdown.

**Comment by Olafkuusik** [comment]
![image](https://user-images.githubusercontent.com/22838368/148902681-c769e2ac-d610-41d6-8018-6d4c97837819.png)

**Comment by Olafkuusik** [comment]
on hoverover the mouse cursor needs to become a pointer hand and the underline can become darker to indicate that this is a clickable area
