### ISSUE TITLE
Add `RSPT` token SVG

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#683]
can be retrieved from here
https://etherscan.io/token/0x016bf078abcacb987f0589a6d3beadd4316922b0

**Comment by Olafkuusik** [comment]
**Dai, USDC and Rari icons in Dashboard:**

![image](https://user-images.githubusercontent.com/22838368/149179735-587fb83f-4ee1-43a0-9875-5bae726c83f6.png)
SVG-s cannot be uploaded here as it is not a supported file format, sending those via discord.

**USDC in Transaction view:**

![image](https://user-images.githubusercontent.com/22838368/149180513-45e9cf0f-2eff-41c2-bc68-9c07ee61ab6d.png)

Dai in Transaction view.
![image](https://user-images.githubusercontent.com/22838368/149180828-c92087ee-939a-4839-9126-1b613dc4adab.png)
