### ISSUE TITLE
Disable Rari pools deposit and show warning message

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#808]
Disable "Deposit" and "Mint" operations
Show the reason message in the sidebar on mouse over

Exact wording
`Deposits into this pool are temporarily disabled due to intermittent unreliability of the underlying Rari pool. Please bear with us while we investigate this issue. More information: https://discord.com/invite/6gauHECShr`

**Comment by lazarmitic** [comment]
Instead of disabling Rari pool, we fixed the underlying issue, closing this one.
