### ISSUE TITLE
support placeholder for translation

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#830]
in i18n we should not do string concatenation. instead all string needs to be translated as a full sentence.
we need to support string like `${str} APR`, where `str` is a protocol name or pool name or whatsoever.
in some language it can be in different position like  `APR ${str}`

it's worth to take a look at [i18next](https://react.i18next.com/)

**Comment by irinelT** [comment]
Translations look good except for 1 case: Settings in Spanish. I believe the width of Slippage should be the same as the width of Language. I am not sure if this is related to changes in this ticket or if requires a new ticket.

![image](https://user-images.githubusercontent.com/98878781/162384079-b81d567d-ea29-4b30-92cf-4260b3cbc879.png)
![image](https://user-images.githubusercontent.com/98878781/162384088-29b6a017-d34c-4113-8439-e3d7b43c871b.png)
![image](https://user-images.githubusercontent.com/98878781/162384615-ce42f4ee-a1a3-4ab3-a847-e90cfd0640e0.png)

**Comment by irinelT** [comment]
Done.

![image](https://user-images.githubusercontent.com/98878781/162798119-7fbf8a91-045b-4800-80f9-a45483adde52.png)
