### ISSUE TITLE
Tooltip arrow gets a delayed shift after it renders

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#833]
when tooltip renders, after 500ms~2000ms, the arrow shifts a bit depending on the anchor width
possible reason: [ref](https://popper.js.org/docs/v1/#modifiers..keepTogether)

**Comment by ShawTim** [comment]
https://user-images.githubusercontent.com/85455/151459330-489a4703-0c23-47a6-bb4c-a0ca928ea350.mp4

**Comment by ShawTim** [comment]
it looks like the `Popper` have a difficulty to find out the anchor element when it renders (i.e. when it renders the first time, the arrow is at its original position with CSS applied, but not actually pointing to the anchor element)
when it updates and triggers re-render, at that time the `Popper` can recognize the anchor element and fix the tooltip and arrow position.
anchor element should be the cause.

**Comment by ShawTim** [comment]
![Peek 2022-03-09 19-03](https://user-images.githubusercontent.com/85455/157431061-9c755794-9177-48a4-96ff-5aa6888d845f.gif)
not a fix but a hack to force the jumping happens right after tooltip open

**Comment by irinelT** [comment]
Looks good to me.
