### ISSUE TITLE
Deploy v2.0 stats contract on ethereum mainnet and update the config in the app

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#849]

**Comment by irinelT** [comment]
@lazarmitic Can you please help with the testing of this item? Some instructions would be helpful, or have someone from fronend team test it until I get the necesery background on this topic.

**Comment by lazarmitic** [comment]
List of things that are affected by stats contract update:

1. Function that calculates USD value of all tokens has been updated - check if USD representation is correct across the application.
2. Function that calculates TVL for Tempus Pools has been updated - check if pool TVL is correctly shown in the UI across the app.

**Comment by irinelT** [comment]
I think that the root couse of issue #1063 is USD calculation representation, so this ticket may still need some work.
