### ISSUE TITLE
percentage misalign on Pool page

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#873]
![image](https://user-images.githubusercontent.com/85455/152066430-50e6720a-d174-4521-b960-33b0574d5dcd.png)

**Comment by lazarmitic** [comment]
I think it should be right aligned as it is

**Comment by ShawTim** [comment]
> I think it should be right aligned as it is

i agree, the problem here looks like becoz of the volume % formatting. if it's `-100.00%`, then it should look like aligned.
so the soln here is to keep it right aligned, but to make sure % are in `000.00%` format.
we can align the arrow as well.

actually, the volume % is hidden now due to #855 , so it should not be a big issue.
