### ISSUE TITLE
UI issues in release 1.6

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#889]

**Comment by Olafkuusik** [comment]
In some places overflow, some places not translated or inconsistently translated, attached screenshots

![spanish_1](https://user-images.githubusercontent.com/22838368/152342167-db13bbe7-0683-4174-b09c-446d7d839a71.PNG)
![spanish_2](https://user-images.githubusercontent.com/22838368/152342170-3ea72aa4-f81b-40ab-9788-6b0c095c3139.PNG)
![spanish_3](https://user-images.githubusercontent.com/22838368/152342171-7e99d5ee-ee68-4f77-90c7-03fc90a0d8d8.PNG)
![spanish_4_tooltip_translation](https://user-images.githubusercontent.com/22838368/152342173-7019de6a-d913-4703-a925-e2fcdf5ae30c.png)
![spanish_5](https://user-images.githubusercontent.com/22838368/152342174-2ba4cc02-347f-45a6-81e8-0fbe393cc060.PNG)
![spanish_6](https://user-images.githubusercontent.com/22838368/152342177-44411af7-5c5e-41a2-b07f-5899c1ea5285.png)
![spanish_7](https://user-images.githubusercontent.com/22838368/152342179-0bcd3925-ef93-4c11-9772-adf55f9a435e.png)
