### ISSUE TITLE
if the estimated APR <0.01%, should block the action and display "insufficient liquidity in the pool"

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#910]
instead of showing negative numbers - although they are correct

**Comment by RTP2016** [comment]
So if the currently collected yield is 1% for example so you get less Principals + Yields, you trade all Yields and drain the amm, it will not cover for already collected 1%

If the result is less than 0.01% APR we should block it on the frontend and display "insufficient liquidity in the pool”

**Comment by Olafkuusik** [comment]
Design proposal for this case:
![image](https://user-images.githubusercontent.com/22838368/155473164-54d8f4a1-8393-48bc-9aff-3077f26d5645.png)

**Comment by Olafkuusik** [comment]
We decided that instead of the red button a disabled state button would be better, uploading another image.
![image](https://user-images.githubusercontent.com/22838368/155519559-9736f667-02bb-4a9c-a9b4-e7a2576b05f9.png)

**Comment by danieledamiani** [comment]
The current disabled button colour is `rgba(0, 0, 0, 0.12)` which it's too light. Shall we create a ad-hoc component instead of reusing Button? Also, where does the link go?

**Comment by danieledamiani** [comment]
![Screenshot 2022-02-24 at 16 29 54](https://user-images.githubusercontent.com/25841025/155566546-f73bdb80-8b6e-4614-9491-a2e63da707ec.png)

**Comment by RTP2016** [comment]
The link will go to the Gitbook docs. I need to update the Gitbook to have a Insufficient Liquidity section in the FAQ.

**Comment by irinelT** [comment]
Is this deployed to staging? It doesn't look good there.

![image](https://user-images.githubusercontent.com/98878781/156197134-2272975f-102c-4555-ab24-ee152524c08b.png)

**Comment by lazarmitic** [comment]
@irinelT check that was added is only for fixed APR, fixed APR goes down if amount you want to deposit is similar to amount of liquidity pool has.

So if you enter pretty large number, and fixed APR goes to less then 0.01%, you will get a message.

Variable APR 0% that you see is not related to insufficient liquidity in the pool, it's probably zero because Yearn API was down at that time.

**Comment by irinelT** [comment]
I see the message on DAI pool but not on USDT.

![image](https://user-images.githubusercontent.com/98878781/157472210-84aeacab-60a3-4c96-9e98-1b201751a2ae.png)

**Comment by lazarmitic** [comment]
I'm able to reproduce this problem with USDT as well on my side. I will try to fix it now.

**Comment by lazarmitic** [comment]
Fixed. Fix deployed to stage and testnet.
