### ISSUE TITLE
Load TVL data only for selected chain

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#926]
If user wallet is not connected and chain is not selected, we should load TVL data for all pools on all chains.

If user wallet is connected, chain is selected, we should load TVL data only for selected chain.

**Comment by irinelT** [comment]
@lazarmitic Not sure if I understand this ticket, but I don't see any TVL when a wallet is not connected.

![image](https://user-images.githubusercontent.com/98878781/155139368-854a0557-8cf1-47ba-87d9-eccf1608de60.png)

**Comment by lazarmitic** [comment]
When wallet is not connected you should see pools from all networks. I will try to reproduce this issue with missing pools when wallet is not connected.

**Comment by irinelT** [comment]
This is working as expect.
