### ISSUE TITLE
After wallet is disconnected from MetaMask user gets request to connect wallet immediately after  

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#932]
We should just revert app to initial state:
1. Show pools from all chains in the dashboard.
2. Show 'Connect Wallet' button.

**Comment by irinelT** [comment]
There is no "connect Wallet" button after disconnect.
It work after refresh, but it should be updated immediately after disconnect without the need of a refresh.

![image](https://user-images.githubusercontent.com/98878781/154915180-d7f66c2a-3bc1-4716-9bee-3fecbbd43541.png)

**Comment by irinelT** [comment]
This is fixed.
