### ISSUE TITLE
Rename `Principals` to `Capital`

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#940]
`principal` => `capital`
`principals` => `capitals`

Including translations: Italian `Capitale` - Spanish `Capital`

**Comment by RTP2016** [comment]
Daniele, reopening as we need to also rename yields >> yield or yield tokens. See the doc shared for these places (hopefully I got all of them!) I think yields sounds a little funny and the plural would be implied in the noun 'tokens'

**Comment by irinelT** [comment]
@RTP2016 We are still using "Yields". Should it be changed to "Yield"?

![image](https://user-images.githubusercontent.com/98878781/154463825-5b4f0150-5c9f-4194-8349-1daf856ca644.png)

**Comment by lazarmitic** [comment]
I think final decision is to use Yields for plural, so in this case it seems correct you are swapping for multiple Yields (Yield Tokens).
