### ISSUE TITLE
VariableAPR service is not properly initialized when wallet is not connected

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#953]

**Comment by irinelT** [comment]
@lazarmitic There is nothing on the screen when the wallet is not connected. Could you please suggest any idea on how to test APR service without a wallet?

**Comment by lazarmitic** [comment]
Hmm, if your wallet is not connected you should see pools from all networks.

![image](https://user-images.githubusercontent.com/7648077/155288078-9e036ed0-ca8d-4e4f-93bf-788cfd3f4045.png)

**Comment by irinelT** [comment]
Ok, I see it on a new browser.
The issue must be we cache on my everyday browser, but that's a completely different thing.
