### ISSUE TITLE
Add missing Chainlink price feeds

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#956]

**Comment by irinelT** [comment]
@lazarmitic Any suggestion on how to test this?

**Comment by lazarmitic** [comment]
Check if all USD prices are correct for Fantom pools, we are fetching token to USD rates from chainlink.

**Comment by irinelT** [comment]
[Chainlink](https://data.chain.link/ethereum/mainnet/crypto-usd/steth-usd) is not responsive for Fantom network, but I was able to get the prices for Ethereum network. It appears that ETH/USD is fetched correctly, but stETH is not. stETH gets the price of ETH.

![image](https://user-images.githubusercontent.com/98878781/155547553-3b18e5f0-5070-409b-8e94-43dadf9e3f65.png)

**Comment by irinelT** [comment]
It was decided that we can use stETH=ETH on frontend.
