### ISSUE TITLE
After token approval is confirmed, Approve button doesn't disactivate, and Execute button does not activate. 

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#962]
Refresh fixes this

**Comment by RTP2016** [comment]
This seems fixed for me. It took a moment but could not reproduce. 

<img width="954" alt="Screenshot 2022-02-10 at 12 14 33" src="https://user-images.githubusercontent.com/17698024/153406785-139175fb-eecd-45e2-94db-fb65d042f4ee.png">

**Comment by lazarmitic** [comment]
This is fixed.

**Comment by irinelT** [comment]
Works like a charm.

![image](https://user-images.githubusercontent.com/98878781/154511724-f1a9ee05-cba2-44a0-a440-2c7e62bc5537.png)
