### ISSUE TITLE
Miscalculation issue in DAI pool

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#965]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/78982233/153394160-863362b1-ad49-4638-a238-c2b25bcfe870.png">

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/155158717-6f5f3087-82e8-4e94-9e99-ac329ff07fff.png)
