### ISSUE TITLE
Update Communtiy menu in Dashboard

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#966]
Update the community dashboard in line with the below

![community menu dashboard](https://user-images.githubusercontent.com/17698024/153394352-a0f6aba3-05e3-46ef-bcb0-3dd9f611d9db.png)

**Comment by irinelT** [comment]
Not bad. I will close the ticket if @Olafkuusik dosent mind the minor issues.

- A litle white space is missing.
- An arrow on the top is missing.
![image](https://user-images.githubusercontent.com/98878781/154273399-69d2faa1-beca-4839-8ee2-6c60951126ca.png)

**Comment by Olafkuusik** [comment]
I don't mind the minor issues, we'll address those at a later point
