### ISSUE TITLE
Popup text formatting broken

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#967]
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/78982233/153394679-5bbac9c8-a8f8-4d57-8da0-00f09868475c.png">

**Comment by davgarai** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/78982233/153395509-e7399b51-08f4-4783-8836-cf0b578f4f72.png">

**Comment by irinelT** [comment]
Formating looks good.

![image](https://user-images.githubusercontent.com/98878781/154239030-a7159649-ec99-4c5d-8c45-a110252a5478.png)
