### ISSUE TITLE
Pool View does not calculate profit & loss numbers at all after entering deposit amount

### ISSUE THREAD

**Issue by davgarai** [tempus-finance/tempus-app#968]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/78982233/153394902-aedc1315-b7c6-44bd-a08a-f27f0a8edc0f.png">

**Comment by davgarai** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/78982233/153395280-e2fe320a-71ff-4185-bdfe-35e96898599f.png">

**Comment by irinelT** [comment]
This is fixed.

![image](https://user-images.githubusercontent.com/98878781/154237501-759e76f2-a511-4765-be63-ec67e02e0595.png)
