### ISSUE TITLE
Add new token icons

### ISSUE THREAD

**Issue by danieledamiani** [tempus-finance/tempus-app#969]
- WETH
- YFI
- yvwETH
- yvUSDT
- yvUSDC
- yvBTC
- yvYFI
- yvDAI
- yvDAI

**Comment by irinelT** [comment]
@Olafkuusik could you please test this or provide me the token icons that need to be on UI so that I can check if its done?

**Comment by Olafkuusik** [comment]
**wETH**
![wETH_40x40_2](https://user-images.githubusercontent.com/22838368/154276341-5b26c98f-dd6d-4306-b2c2-595e54e3eba0.svg)
![wETH_20x20_2](https://user-images.githubusercontent.com/22838368/154276345-e8e94f41-4f95-45fc-a4bd-b1d1090b0e79.svg)
**YFI**
![YFI_40x40](https://user-images.githubusercontent.com/22838368/154276539-ead54536-eb1c-4261-a780-c2226f41c5f6.svg)
![YFI_20x20](https://user-images.githubusercontent.com/22838368/154276556-4cc01839-2d84-4c2a-948f-99bf42900aba.svg)
**yvwETH**
![yvwETH_40x40](https://user-images.githubusercontent.com/22838368/154276849-8fa9ef48-3fd4-451b-be13-178282950374.svg)
![yvwETH_20x20](https://user-images.githubusercontent.com/22838368/154276860-9d7acee6-d116-4798-a8e3-5c43ce73c47b.svg)
**yvUSDT**
![yvUSDT_40x40](https://user-images.githubusercontent.com/22838368/154276941-7cfee27d-d7a7-448a-8652-c413dc5e8cdd.svg)
![yvUSDT_20x20](https://user-images.githubusercontent.com/22838368/154276946-7296281d-5c9a-4ba0-b560-27fd92013091.svg)
**yvUSDC**
![yvUSDC_40x40](https://user-images.githubusercontent.com/22838368/154277114-13bd7e0a-6f56-4d63-91e9-f398f3b157aa.svg)
![yvUSDT_20x20](https://user-images.githubusercontent.com/22838368/154277127-a599671c-582d-495e-9fdc-510a08fe1cc6.svg)
**yvBTC**
![yvwBTC_40x40](https://user-images.githubusercontent.com/22838368/154277190-85255fd4-7e00-45f1-ab15-11dbf36041b2.svg)
![yvwBTC_20x20](https://user-images.githubusercontent.com/22838368/154277202-8ee5341d-d6bd-46c8-aeda-da4a0514e7fa.svg)
**yvYFI**
![yvYFI_40x40](https://user-images.githubusercontent.com/22838368/154277258-476b85d3-0780-4254-bd71-6718e09490e1.svg)
![yvYFI_20x20](https://user-images.githubusercontent.com/22838368/154277269-15f0ddef-9f27-4167-9e3c-a9bad5299cb0.svg)
**yvDAI**
![yvDAI_40x40](https://user-images.githubusercontent.com/22838368/154277451-2893c440-99d9-4e8a-b70d-ebecbcdc5a86.svg)
![yvDAI_20x20](https://user-images.githubusercontent.com/22838368/154277456-022421b0-78aa-4b7a-84df-dece91f0c583.svg)
**DAI**
![Dai_40x40](https://user-images.githubusercontent.com/22838368/154277490-e2c5a237-772e-4773-80d9-d50a378becc1.svg)
![Dai_20x20](https://user-images.githubusercontent.com/22838368/154277498-129a4a08-305e-4709-a696-6e7ce1dbbb50.svg)

**Comment by irinelT** [comment]
@Olafkuusik Are you sure that is the right icon for smal yvUSDC?
I think that this can be closed.

![image](https://user-images.githubusercontent.com/98878781/154322653-c0b5b3c2-323e-4094-a08a-e8709cc323d3.png)
