### ISSUE TITLE
Use smallest possible spot price for Fantom pools

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#972]

**Comment by irinelT** [comment]
@lazarmitic Could you please provide any instructions for this ticket?

**Comment by lazarmitic** [comment]
Spot price affects Fixed APR shown on the dashboard. I'm not sure what's the best way to verify if the value shown is correct. Maybe Cristiano or George can provide math formula for it and you can calculate it and see if it matches with value shown in the the app.

**Comment by irinelT** [comment]
This will be moved to next release as it cannot be tested now.

**Comment by irinelT** [comment]
APR was checked and matching Prod.
