### ISSUE TITLE
Remove !important flag from notification content class

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#975]
Pass wrap style to typography instead

**Comment by irinelT** [comment]
Does this apply to button text? I still see button text wrap.

![image](https://user-images.githubusercontent.com/98878781/162285779-5f1f1915-6a68-4e28-bdef-28fdbd054492.png)

**Comment by iamvukasin** [comment]
No, it is more CSS code cleanup. That one is connected with #1133.

**Comment by irinelT** [comment]
Ok, closing this ticket.
