### ISSUE TITLE
After depositing the side menu options do not activate for allowed actions 

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#977]
After depositing the side menu options do not activate for allowed actions e.g., withdraw, swap, mint. Only after refreshing 

<img width="521" alt="Screenshot 2022-02-10 at 12 17 19" src="https://user-images.githubusercontent.com/17698024/153407572-94710829-d544-4f16-b0c2-765cef6664af.png">

**Comment by irinelT** [comment]
This is fixed. I created a new account with 0 deposit and all Withdraw, Mint and Swap were available right after deposit.

![image](https://user-images.githubusercontent.com/98878781/154500389-a27c99ff-e29e-4cf2-8fc9-8b49c6754f9c.png)
