### ISSUE TITLE
Add missing token precisions for backing tokens in constants file

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#981]

**Comment by irinelT** [comment]
Precision has been set in these 2 files. We yet need to find the UI pice that reflects these changes.
https://github.com/tempus-finance/tempus-app/pull/983/files

**Comment by irinelT** [comment]
I found that the precision is set in the files and it is reflected correctly on UI.

![image](https://user-images.githubusercontent.com/98878781/154310665-d8a70f71-2bca-449b-8b59-d0456afc19e8.png)
