### ISSUE TITLE
Missing the deposit amount $ equivalent

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#985]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand WBTC.
3. Manage.
4. Navigate to Deposit or to Mint. (both are not working)
5. Pick WBTC in "From" dropdown box.
6. Type in "1".

Expected:
The equvalent of 1 WBTC is displayed in $ under it.

Actual: **(Note: this happens on Mint page also)**
![image](https://user-images.githubusercontent.com/98878781/153411605-b5b44ab2-eeb6-4b98-9cac-483e19d4b629.png)

**Comment by lazarmitic** [comment]
WBTC was removed from the app.

**Comment by irinelT** [comment]
This issue is still reproducible on WETH deposit.

![image](https://user-images.githubusercontent.com/98878781/153849887-a6476e0a-6554-479b-a677-9301a8d5109c.png)

**Comment by irinelT** [comment]
This issue is not reproducible any more.
