### ISSUE TITLE
Deposit amount input field is blocked from typing

### ISSUE THREAD

**Issue by irinelT** [tempus-finance/tempus-app#986]
Prerequest:

- Connect MetaMask to Tempus App
- Switch MetaMask to Fantom network ([details](https://docs.fantom.foundation/tutorials/set-up-metamask))

Steps:

1. Navigate to https://tempus-app-testnet-v2.web.app/
2. Expand DAI.
3. Manage.
4. Pick DAI in "From" dropdown box.
5. Click on deposite amount input field.

Expected:
The text imput cursor should blink within input field.

Actual:
![image](https://user-images.githubusercontent.com/98878781/153419029-cb5e36cc-9c47-4574-ace0-bc66fbebeb3a.png)

**Comment by irinelT** [comment]
This is not reproducible any more
![image](https://user-images.githubusercontent.com/98878781/153596222-6a2ae104-d0d0-4ccc-baf8-d45a190c4075.png)

**Comment by irinelT** [comment]
The same issue appeared on WETH Mint.

![image](https://user-images.githubusercontent.com/98878781/154939046-ac42a69a-9e37-4e43-90a9-c4d3f4f7f7a4.png)

**Comment by lazarmitic** [comment]
Just to clarify, this happens because pool has negative yield. We need to make UX better here.

**Comment by RTP2016** [comment]
This scenario is for when a pool is in negative yield
- Fronted end to change logic on the label to display when negative yield
- Design to provide the new label

**Comment by RTP2016** [comment]
Deposits are currently disabled as this pool is currently experiencing negative yields. Please check our [docs](https://docs.tempus.finance/community/faq#why-would-a-pool-have-a-negative-yield) for more information. 

Spanish: Los depósitos están deshabilitados actualmente ya que este grupo está experimentando rendimientos negativos. Consulte nuestros documentos para obtener más información.

Italian: I depositi sono attualmente disabilitati poiché questo pool sta attualmente registrando rendimenti negativi. Si prega di controllare i nostri documenti per ulteriori informazioni.

**Comment by irinelT** [comment]
Not able to test now, moving to next release. Requires negative yield pool.
