### ISSUE TITLE
Execute button does not become active after approval for swap

### ISSUE THREAD

**Issue by RTP2016** [tempus-finance/tempus-app#988]
Steps: 
1. Swap
2. Max principals (capital) 
3. To: Yields
4. Approve

Issue: 
After approval,
<img width="772" alt="Screenshot 2022-02-10 at 15 01 41" src="https://user-images.githubusercontent.com/17698024/153434771-8609451b-5536-417d-953c-2b4f600096b8.png">
 the execute button does not activate. Need to refresh the page.

**Comment by RTP2016** [comment]
<img width="634" alt="Screenshot 2022-02-11 at 11 32 25" src="https://user-images.githubusercontent.com/17698024/153584478-5eec8c44-2990-4117-bcb0-4426f8315cfe.png">
Issue persists

**Comment by lazarmitic** [comment]
Approve button fixed, that should fix this one as well. Please re-test.

**Comment by irinelT** [comment]
This works as expected.

![image](https://user-images.githubusercontent.com/98878781/153854677-30aa67b6-7c2a-48ed-b9d1-670c8050bf0a.png)

**Comment by irinelT** [comment]
@RTP2016 

Execute button works well on "Swap".
On "Withdraw", its necesery to have both tokens approved. Is this expected?

![image](https://user-images.githubusercontent.com/98878781/153855726-275a7dd2-ea2e-4d2b-b302-ac864eac6133.png)

**Comment by RTP2016** [comment]
> @RTP2016
> 
> Execute button works well on "Swap". On "Withdraw", its necesery to have both tokens approved. Is this expected?
> 
> ![image](https://user-images.githubusercontent.com/98878781/153855726-275a7dd2-ea2e-4d2b-b302-ac864eac6133.png)

It's requiring you to approve the Yield Tokens because you have an amount in the input box. If you delete the amount in the bottom input field it should allow you to execute.  Each token requires approval separately.
