### ISSUE TITLE
Update FixedAPR on every poll interval instead of on every block

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#991]
Block time on Fantom is 0.9 seconds, and app is getting rekt by fetching fixed APR on every block (every 0.9 seconds). Instead of fetching on every block, we should fetch on every poll interval that we can set to any time interval we want to.

**Comment by irinelT** [comment]
I don't see any network activity when parked on Dashboard page. Not sure if this is the right way to test but it looks like APR is fetched only on refresh.

![image](https://user-images.githubusercontent.com/98878781/155186587-5c0675d3-ab6f-4645-9225-22cd36ddeded.png)

**Comment by lazarmitic** [comment]
Requests go through MetaMask plugin and those are not shown in network tab. Maybe there is a way to inspect plugin network activity.

**Comment by irinelT** [comment]
I did observe APR slowly changing. This can be closed.

![image](https://user-images.githubusercontent.com/98878781/155193242-3723e90a-bcfe-4d1b-93d7-0d2e593cbbb7.png)
