### ISSUE TITLE
Redirect users to dashboard who change the network while in transaction view

### ISSUE THREAD

**Issue by Olafkuusik** [tempus-finance/tempus-app#993]
2 cases:

1. User is on network A (ex. Ethereum) -> selects a pool -> Manage -> Transaction view -> Changes network to B (ex. Fantom) from header or Metamask directly
User should be redirected to dashboard with network B pools.

2. User enters direct URL to a pool on network B but user's metamask is set to network A, instead of showing the user network B Pool transaction view user should be redirected to dashboard with network A pools.

**Comment by irinelT** [comment]
This is almost working. You need to refresh to get it to work as expected. "Manage" doesnt work if you dont refresh. I will add low priority since the esence is right.

![image](https://user-images.githubusercontent.com/98878781/154706037-200e365f-775f-44a5-82f7-4d59cf179585.png)

**Comment by irinelT** [comment]
Original issue is fixed.
Additional issue will be addressed in a separate ticket #1124 .
