### ISSUE TITLE
refactor infoTooltip to support external open state

### ISSUE THREAD

**Issue by ShawTim** [tempus-finance/tempus-app#995]
currently `infoTooltip` manage state locally. most of the time we can just use it brainlessly.
however for some case if we want to manage the state outside, we may need to do some hacks like make a `click` to control the open state:
ref: https://github.com/tempus-finance/tempus-app/pull/994#discussion_r804473013

should refactor `infoTooltip` to accept 1 flag (e.g. `useExternalOpenState`) and 1 state (e.g. `externalOpen`)
if `useExternalOpenState` is true, use `externalOpen` instead of local state

**Comment by ShawTim** [comment]
to test this:
- test normal tooltip and see whether it works properly
- refer to #994 , when you are in unsupported network, click on the wallet will pop you a tooltip. test whether it works properly, click "select network" and test whether the original tooltip closes

**Comment by irinelT** [comment]
It works, but you need to click twice on MetaMask in order to select it. Can we improve this (click once)?

![Double click to switch network](https://user-images.githubusercontent.com/98878781/155744759-1cffe325-176c-4dba-bbac-83c47ca98906.gif)

**Comment by ShawTim** [comment]
this should be fixed in next deployment

**Comment by irinelT** [comment]
Works perfectly.
