### ISSUE TITLE
Variable APR should be updated on every poll interval instead of on every block 

### ISSUE THREAD

**Issue by lazarmitic** [tempus-finance/tempus-app#996]

**Comment by irinelT** [comment]
I don't see any network activity when parked on Dashboard page. Not sure if this is the right way to test but it looks like APR is fetched only on refresh.

![image](https://user-images.githubusercontent.com/98878781/155186587-5c0675d3-ab6f-4645-9225-22cd36ddeded.png)

**Comment by lazarmitic** [comment]
See my comment for Fixed apr fetches

**Comment by irinelT** [comment]
I did observe APR slowly changing. This can be closed.

![image](https://user-images.githubusercontent.com/98878781/155193242-3723e90a-bcfe-4d1b-93d7-0d2e593cbbb7.png)

**Comment by irinelT** [comment]
The APR is slowly changing. It works.

![image](https://user-images.githubusercontent.com/98878781/155198464-d8b836c4-833c-46a6-b6aa-902489d077e5.png)
